/**
 * The Olympiad reports' labels — the tables' headings and the lines round
 * them. The headline and the lede come with the report, written by the
 * collector in the same language (scripts/feed/report-words.mjs).
 */
export interface ReportWords {
  section: string;
  topMatches: string;
  standings: string;
  team: string;
  mp: string;
  gp: string;
  upsets: string;
  winner: string;
  loser: string;
  difference: string;
  games: string;
  whiteWins: string;
  blackWins: string;
  draws: string;
  inNumbers: string;
  longest: string;
  openings: string;
  moves: string;
  rounds: string;
  stories: string;
  counted: string;
  official: string;
  site: string;
  broadcast: string;
}

const en: ReportWords = {
  section: 'The Chess Olympiad', topMatches: 'Top matches', standings: 'The table', team: 'Team',
  mp: 'Match points', gp: 'Game points', upsets: 'Upsets on the ratings', winner: 'Won', loser: 'Lost',
  difference: 'Rating gap', games: 'Games', whiteWins: 'White won', blackWins: 'Black won', draws: 'Drawn',
  inNumbers: 'In numbers', longest: 'The longest game', openings: 'The most played openings',
  moves: 'moves', rounds: 'Round by round', stories: 'The games, move by move',
  counted: 'Counted from the games of the official broadcast: a match counts when all four of its boards were relayed. Teams level on match points are shown by game points; the official order uses the event’s tiebreaks.',
  official: 'Official standings', site: 'Official site', broadcast: 'The official broadcast on Lichess',
};

export const REPORT_WORDS: Record<string, ReportWords> = {
  en,
  bg: { section: 'Шахматната олимпиада', topMatches: 'Първите мачове', standings: 'Класирането', team: 'Отбор', mp: 'Мачови точки', gp: 'Точки от партии', upsets: 'Изненади по рейтинг', winner: 'Спечели', loser: 'Загуби', difference: 'Разлика', games: 'Партии', whiteWins: 'Победи на белите', blackWins: 'Победи на черните', draws: 'Реми', inNumbers: 'В числа', longest: 'Най-дългата партия', openings: 'Най-играните дебюти', moves: 'хода', rounds: 'Кръг по кръг', stories: 'Партиите, ход по ход', counted: 'Преброено от партиите в официалното излъчване: мачът се брои, когато и четирите му дъски са предавани. Отборите с равни мачови точки са подредени по точки от партии; официалното класиране използва допълнителните показатели на турнира.', official: 'Официално класиране', site: 'Официален сайт', broadcast: 'Официалното излъчване в Lichess' },
  de: { section: 'Die Schacholympiade', topMatches: 'Spitzenkämpfe', standings: 'Die Tabelle', team: 'Mannschaft', mp: 'Mannschaftspunkte', gp: 'Brettpunkte', upsets: 'Überraschungen nach Elo', winner: 'Gewonnen', loser: 'Verloren', difference: 'Elo-Abstand', games: 'Partien', whiteWins: 'Weiß gewann', blackWins: 'Schwarz gewann', draws: 'Remis', inNumbers: 'In Zahlen', longest: 'Die längste Partie', openings: 'Die meistgespielten Eröffnungen', moves: 'Züge', rounds: 'Runde für Runde', stories: 'Die Partien, Zug für Zug', counted: 'Gezählt aus den Partien der offiziellen Übertragung: Ein Kampf zählt, wenn alle vier Bretter übertragen wurden. Punktgleiche Mannschaften stehen hier nach Brettpunkten; die offizielle Reihenfolge nutzt die Feinwertungen des Turniers.', official: 'Offizielle Tabelle', site: 'Offizielle Website', broadcast: 'Die offizielle Übertragung auf Lichess' },
  fr: { section: 'L’Olympiade d’échecs', topMatches: 'Les matchs de tête', standings: 'Le classement', team: 'Équipe', mp: 'Points de match', gp: 'Points de partie', upsets: 'Surprises au classement Elo', winner: 'Gagné', loser: 'Perdu', difference: 'Écart Elo', games: 'Parties', whiteWins: 'Gains des Blancs', blackWins: 'Gains des Noirs', draws: 'Nulles', inNumbers: 'En chiffres', longest: 'La plus longue partie', openings: 'Les ouvertures les plus jouées', moves: 'coups', rounds: 'Ronde par ronde', stories: 'Les parties, coup par coup', counted: 'Compté à partir des parties de la retransmission officielle : un match compte quand ses quatre échiquiers ont été retransmis. Les équipes à égalité de points de match sont classées ici aux points de partie ; l’ordre officiel utilise les départages du tournoi.', official: 'Classement officiel', site: 'Site officiel', broadcast: 'La retransmission officielle sur Lichess' },
  es: { section: 'La Olimpiada de Ajedrez', topMatches: 'Los primeros encuentros', standings: 'La clasificación', team: 'Equipo', mp: 'Puntos de match', gp: 'Puntos de partida', upsets: 'Sorpresas por Elo', winner: 'Ganó', loser: 'Perdió', difference: 'Diferencia Elo', games: 'Partidas', whiteWins: 'Ganaron blancas', blackWins: 'Ganaron negras', draws: 'Tablas', inNumbers: 'En cifras', longest: 'La partida más larga', openings: 'Las aperturas más jugadas', moves: 'jugadas', rounds: 'Ronda a ronda', stories: 'Las partidas, jugada a jugada', counted: 'Contado a partir de las partidas de la retransmisión oficial: un encuentro cuenta cuando se retransmitieron sus cuatro tableros. Los equipos empatados a puntos de match se ordenan aquí por puntos de partida; el orden oficial usa los desempates del torneo.', official: 'Clasificación oficial', site: 'Web oficial', broadcast: 'La retransmisión oficial en Lichess' },
  it: { section: 'Le Olimpiadi degli scacchi', topMatches: 'I match di vertice', standings: 'La classifica', team: 'Squadra', mp: 'Punti match', gp: 'Punti partita', upsets: 'Sorprese per Elo', winner: 'Vinto', loser: 'Perso', difference: 'Differenza Elo', games: 'Partite', whiteWins: 'Vittorie del Bianco', blackWins: 'Vittorie del Nero', draws: 'Patte', inNumbers: 'In numeri', longest: 'La partita più lunga', openings: 'Le aperture più giocate', moves: 'mosse', rounds: 'Turno per turno', stories: 'Le partite, mossa per mossa', counted: 'Contato dalle partite della diretta ufficiale: un match conta quando tutte e quattro le scacchiere sono state trasmesse. Le squadre a pari punti match sono ordinate qui per punti partita; l’ordine ufficiale usa gli spareggi del torneo.', official: 'Classifica ufficiale', site: 'Sito ufficiale', broadcast: 'La diretta ufficiale su Lichess' },
  'pt-br': { section: 'A Olimpíada de Xadrez', topMatches: 'Os confrontos principais', standings: 'A tabela', team: 'Equipe', mp: 'Pontos de match', gp: 'Pontos de partida', upsets: 'Zebras pelo rating', winner: 'Venceu', loser: 'Perdeu', difference: 'Diferença de rating', games: 'Partidas', whiteWins: 'Vitórias das brancas', blackWins: 'Vitórias das pretas', draws: 'Empates', inNumbers: 'Em números', longest: 'A partida mais longa', openings: 'As aberturas mais jogadas', moves: 'lances', rounds: 'Rodada a rodada', stories: 'As partidas, lance a lance', counted: 'Contado a partir das partidas da transmissão oficial: um confronto conta quando os quatro tabuleiros foram transmitidos. Equipes empatadas em pontos de match aparecem aqui por pontos de partida; a ordem oficial usa os desempates do torneio.', official: 'Classificação oficial', site: 'Site oficial', broadcast: 'A transmissão oficial no Lichess' },
  ru: { section: 'Шахматная олимпиада', topMatches: 'Главные матчи', standings: 'Таблица', team: 'Команда', mp: 'Командные очки', gp: 'Личные очки', upsets: 'Сенсации по рейтингу', winner: 'Выиграл(а)', loser: 'Проиграл(а)', difference: 'Разница', games: 'Партии', whiteWins: 'Победы белых', blackWins: 'Победы чёрных', draws: 'Ничьи', inNumbers: 'В цифрах', longest: 'Самая длинная партия', openings: 'Самые популярные дебюты', moves: 'ходов', rounds: 'Тур за туром', stories: 'Партии, ход за ходом', counted: 'Подсчитано по партиям официальной трансляции: матч учитывается, если транслировались все четыре доски. Команды с равными командными очками здесь упорядочены по личным очкам; официальный порядок определяют дополнительные показатели турнира.', official: 'Официальная таблица', site: 'Официальный сайт', broadcast: 'Официальная трансляция на Lichess' },
  pl: { section: 'Olimpiada szachowa', topMatches: 'Czołowe mecze', standings: 'Tabela', team: 'Drużyna', mp: 'Punkty meczowe', gp: 'Punkty partii', upsets: 'Niespodzianki rankingowe', winner: 'Wygrana', loser: 'Przegrana', difference: 'Różnica', games: 'Partie', whiteWins: 'Wygrane białych', blackWins: 'Wygrane czarnych', draws: 'Remisy', inNumbers: 'W liczbach', longest: 'Najdłuższa partia', openings: 'Najczęstsze otwarcia', moves: 'ruchów', rounds: 'Runda po rundzie', stories: 'Partie, ruch po ruchu', counted: 'Policzone z partii oficjalnej transmisji: mecz liczy się, gdy transmitowano wszystkie cztery szachownice. Drużyny z równą liczbą punktów meczowych są tu ułożone według punktów partii; oficjalna kolejność korzysta z punktacji pomocniczej turnieju.', official: 'Oficjalna tabela', site: 'Oficjalna strona', broadcast: 'Oficjalna transmisja na Lichess' },
  cs: { section: 'Šachová olympiáda', topMatches: 'Nejvyšší zápasy', standings: 'Tabulka', team: 'Družstvo', mp: 'Zápasové body', gp: 'Partiové body', upsets: 'Překvapení podle ratingu', winner: 'Vyhrál(a)', loser: 'Prohrál(a)', difference: 'Rozdíl', games: 'Partie', whiteWins: 'Výhry bílých', blackWins: 'Výhry černých', draws: 'Remízy', inNumbers: 'V číslech', longest: 'Nejdelší partie', openings: 'Nejhranější zahájení', moves: 'tahů', rounds: 'Kolo po kole', stories: 'Partie, tah po tahu', counted: 'Spočítáno z partií oficiálního přenosu: zápas se počítá, když byly přenášeny všechny čtyři šachovnice. Družstva se stejnými zápasovými body jsou zde seřazena podle partiových bodů; oficiální pořadí používá pomocná hodnocení turnaje.', official: 'Oficiální tabulka', site: 'Oficiální web', broadcast: 'Oficiální přenos na Lichess' },
  nl: { section: 'De Schaakolympiade', topMatches: 'De topwedstrijden', standings: 'De stand', team: 'Team', mp: 'Matchpunten', gp: 'Bordpunten', upsets: 'Verrassingen op rating', winner: 'Gewonnen', loser: 'Verloren', difference: 'Ratingverschil', games: 'Partijen', whiteWins: 'Winst wit', blackWins: 'Winst zwart', draws: 'Remises', inNumbers: 'In cijfers', longest: 'De langste partij', openings: 'De meest gespeelde openingen', moves: 'zetten', rounds: 'Ronde voor ronde', stories: 'De partijen, zet voor zet', counted: 'Geteld uit de partijen van de officiële uitzending: een wedstrijd telt als alle vier de borden zijn uitgezonden. Teams met gelijke matchpunten staan hier op bordpunten; de officiële volgorde gebruikt de weerstandspunten van het toernooi.', official: 'Officiële stand', site: 'Officiële website', broadcast: 'De officiële uitzending op Lichess' },
  sv: { section: 'Schackolympiaden', topMatches: 'Toppmatcherna', standings: 'Tabellen', team: 'Lag', mp: 'Matchpoäng', gp: 'Partipoäng', upsets: 'Skrällar på rating', winner: 'Vann', loser: 'Förlorade', difference: 'Ratingskillnad', games: 'Partier', whiteWins: 'Vit vann', blackWins: 'Svart vann', draws: 'Remier', inNumbers: 'I siffror', longest: 'Det längsta partiet', openings: 'De mest spelade öppningarna', moves: 'drag', rounds: 'Rond för rond', stories: 'Partierna, drag för drag', counted: 'Räknat ur partierna i den officiella sändningen: en match räknas när alla fyra bord sändes. Lag med lika matchpoäng visas här efter partipoäng; den officiella ordningen använder turneringens särskiljning.', official: 'Officiell tabell', site: 'Officiell webbplats', broadcast: 'Den officiella sändningen på Lichess' },
  da: { section: 'Skakolympiaden', topMatches: 'Topkampene', standings: 'Stillingen', team: 'Hold', mp: 'Matchpoint', gp: 'Partipoint', upsets: 'Overraskelser på rating', winner: 'Vandt', loser: 'Tabte', difference: 'Ratingforskel', games: 'Partier', whiteWins: 'Hvid vandt', blackWins: 'Sort vandt', draws: 'Remis', inNumbers: 'I tal', longest: 'Det længste parti', openings: 'De mest spillede åbninger', moves: 'træk', rounds: 'Runde for runde', stories: 'Partierne, træk for træk', counted: 'Talt ud fra partierne i den officielle transmission: en kamp tæller, når alle fire brætter blev transmitteret. Hold med lige mange matchpoint vises her efter partipoint; den officielle rækkefølge bruger turneringens korrektion.', official: 'Officiel stilling', site: 'Officielt websted', broadcast: 'Den officielle transmission på Lichess' },
  no: { section: 'Sjakkolympiaden', topMatches: 'Toppkampene', standings: 'Tabellen', team: 'Lag', mp: 'Matchpoeng', gp: 'Partipoeng', upsets: 'Overraskelser på rating', winner: 'Vant', loser: 'Tapte', difference: 'Ratingforskjell', games: 'Partier', whiteWins: 'Hvit vant', blackWins: 'Svart vant', draws: 'Remis', inNumbers: 'I tall', longest: 'Det lengste partiet', openings: 'De mest spilte åpningene', moves: 'trekk', rounds: 'Runde for runde', stories: 'Partiene, trekk for trekk', counted: 'Telt fra partiene i den offisielle sendingen: en kamp teller når alle fire brettene ble sendt. Lag med like mange matchpoeng vises her etter partipoeng; den offisielle rekkefølgen bruker turneringens korreksjon.', official: 'Offisiell tabell', site: 'Offisiell nettside', broadcast: 'Den offisielle sendingen på Lichess' },
  fi: { section: 'Shakkiolympialaiset', topMatches: 'Kärkiottelut', standings: 'Taulukko', team: 'Joukkue', mp: 'Ottelupisteet', gp: 'Pelipisteet', upsets: 'Yllätykset vahvuusluvulla', winner: 'Voitti', loser: 'Hävisi', difference: 'Ero', games: 'Pelit', whiteWins: 'Valkean voitot', blackWins: 'Mustan voitot', draws: 'Tasapelit', inNumbers: 'Numeroina', longest: 'Pisin peli', openings: 'Pelatuimmat avaukset', moves: 'siirtoa', rounds: 'Kierros kierrokselta', stories: 'Pelit siirto siirrolta', counted: 'Laskettu virallisen lähetyksen peleistä: ottelu lasketaan, kun kaikki neljä lautaa lähetettiin. Ottelupisteissä tasan olevat joukkueet on järjestetty tässä pelipisteillä; virallinen järjestys käyttää turnauksen tasapisteratkaisuja.', official: 'Virallinen taulukko', site: 'Virallinen sivusto', broadcast: 'Virallinen lähetys Lichessissä' },
  hu: { section: 'A sakkolimpia', topMatches: 'Az élmérkőzések', standings: 'A tabella', team: 'Csapat', mp: 'Csapatpont', gp: 'Játszmapont', upsets: 'Meglepetések Élő-pont szerint', winner: 'Nyert', loser: 'Vesztett', difference: 'Különbség', games: 'Játszmák', whiteWins: 'Világos nyert', blackWins: 'Sötét nyert', draws: 'Döntetlen', inNumbers: 'Számokban', longest: 'A leghosszabb játszma', openings: 'A leggyakoribb megnyitások', moves: 'lépés', rounds: 'Fordulóról fordulóra', stories: 'A játszmák, lépésről lépésre', counted: 'A hivatalos közvetítés játszmáiból számolva: egy mérkőzés akkor számít, ha mind a négy táblát közvetítették. Az azonos csapatpontú csapatok itt játszmapont szerint állnak; a hivatalos sorrend a verseny holtverseny-eldöntési szabályait használja.', official: 'Hivatalos tabella', site: 'Hivatalos oldal', broadcast: 'A hivatalos közvetítés a Lichessen' },
  tr: { section: 'Satranç Olimpiyatı', topMatches: 'Üst eşleşmeler', standings: 'Puan durumu', team: 'Takım', mp: 'Maç puanı', gp: 'Oyun puanı', upsets: 'Reytinge göre sürprizler', winner: 'Kazandı', loser: 'Kaybetti', difference: 'Fark', games: 'Oyunlar', whiteWins: 'Beyaz kazandı', blackWins: 'Siyah kazandı', draws: 'Berabere', inNumbers: 'Rakamlarla', longest: 'En uzun oyun', openings: 'En çok oynanan açılışlar', moves: 'hamle', rounds: 'Tur tur', stories: 'Oyunlar, hamle hamle', counted: 'Resmi yayındaki oyunlardan sayıldı: bir eşleşme, dört masası da yayınlandığında sayılır. Maç puanı eşit takımlar burada oyun puanına göre sıralanır; resmi sıralama turnuvanın eşitlik bozma ölçütlerini kullanır.', official: 'Resmi puan durumu', site: 'Resmi site', broadcast: 'Lichess’teki resmi yayın' },
  el: { section: 'Η Σκακιστική Ολυμπιάδα', topMatches: 'Οι κορυφαίοι αγώνες', standings: 'Η βαθμολογία', team: 'Ομάδα', mp: 'Βαθμοί αγώνα', gp: 'Βαθμοί παρτίδων', upsets: 'Εκπλήξεις με βάση το Elo', winner: 'Κέρδισε', loser: 'Έχασε', difference: 'Διαφορά', games: 'Παρτίδες', whiteWins: 'Νίκες λευκών', blackWins: 'Νίκες μαύρων', draws: 'Ισοπαλίες', inNumbers: 'Σε αριθμούς', longest: 'Η μεγαλύτερη παρτίδα', openings: 'Τα πιο συχνά ανοίγματα', moves: 'κινήσεις', rounds: 'Γύρο γύρο', stories: 'Οι παρτίδες, κίνηση προς κίνηση', counted: 'Μετρημένο από τις παρτίδες της επίσημης μετάδοσης: ένας αγώνας μετράει όταν μεταδόθηκαν και οι τέσσερις σκακιέρες. Οι ομάδες με ίσους βαθμούς αγώνα κατατάσσονται εδώ με τους βαθμούς παρτίδων· η επίσημη σειρά χρησιμοποιεί τα κριτήρια ισοβαθμίας του τουρνουά.', official: 'Επίσημη βαθμολογία', site: 'Επίσημος ιστότοπος', broadcast: 'Η επίσημη μετάδοση στο Lichess' },
  he: { section: 'אולימפיאדת השחמט', topMatches: 'המפגשים המובילים', standings: 'הטבלה', team: 'קבוצה', mp: 'נקודות משחק', gp: 'נקודות לוח', upsets: 'הפתעות לפי דירוג', winner: 'ניצח/ה', loser: 'הפסיד/ה', difference: 'פער', games: 'משחקים', whiteWins: 'ניצחונות לבן', blackWins: 'ניצחונות שחור', draws: 'תיקו', inNumbers: 'במספרים', longest: 'המשחק הארוך ביותר', openings: 'הפתיחות הנפוצות ביותר', moves: 'מסעים', rounds: 'סיבוב אחר סיבוב', stories: 'המשחקים, מסע אחר מסע', counted: 'נספר מתוך משחקי השידור הרשמי: מפגש נספר כשכל ארבעת הלוחות שלו שודרו. קבוצות בשוויון נקודות משחק מוצגות כאן לפי נקודות לוח; הסדר הרשמי משתמש בשוברי השוויון של הטורניר.', official: 'הטבלה הרשמית', site: 'האתר הרשמי', broadcast: 'השידור הרשמי ב-Lichess' },
  ar: { section: 'أولمبياد الشطرنج', topMatches: 'أبرز المباريات', standings: 'الترتيب', team: 'الفريق', mp: 'نقاط المباريات', gp: 'نقاط الأدوار', upsets: 'مفاجآت التصنيف', winner: 'فاز', loser: 'خسر', difference: 'الفارق', games: 'الأدوار', whiteWins: 'فوز الأبيض', blackWins: 'فوز الأسود', draws: 'تعادل', inNumbers: 'بالأرقام', longest: 'أطول دور', openings: 'أكثر الافتتاحيات لعبًا', moves: 'نقلة', rounds: 'جولة بجولة', stories: 'الأدوار، نقلة بنقلة', counted: 'محسوب من أدوار البث الرسمي: تُحتسب المباراة حين تُبث طاولاتها الأربع كلها. الفرق المتساوية في نقاط المباريات مرتبة هنا حسب نقاط الأدوار؛ والترتيب الرسمي يعتمد معايير كسر التعادل في البطولة.', official: 'الترتيب الرسمي', site: 'الموقع الرسمي', broadcast: 'البث الرسمي على Lichess' },
  hi: { section: 'शतरंज ओलंपियाड', topMatches: 'शीर्ष मुक़ाबले', standings: 'तालिका', team: 'टीम', mp: 'मैच अंक', gp: 'बाज़ी अंक', upsets: 'रेटिंग के हिसाब से उलटफेर', winner: 'जीते', loser: 'हारे', difference: 'अंतर', games: 'बाज़ियाँ', whiteWins: 'सफ़ेद की जीत', blackWins: 'काले की जीत', draws: 'ड्रॉ', inNumbers: 'आँकड़ों में', longest: 'सबसे लंबी बाज़ी', openings: 'सबसे ज़्यादा खेली गई ओपनिंग', moves: 'चालें', rounds: 'राउंड-दर-राउंड', stories: 'बाज़ियाँ, चाल-दर-चाल', counted: 'आधिकारिक प्रसारण की बाज़ियों से गिना गया: कोई मुक़ाबला तब गिना जाता है जब उसके चारों बोर्ड प्रसारित हुए हों। बराबर मैच अंकों वाली टीमें यहाँ बाज़ी अंकों से क्रम में हैं; आधिकारिक क्रम टूर्नामेंट के टाई-ब्रेक से तय होता है।', official: 'आधिकारिक तालिका', site: 'आधिकारिक साइट', broadcast: 'Lichess पर आधिकारिक प्रसारण' },
  ja: { section: 'チェス・オリンピアード', topMatches: '上位の対戦', standings: '順位', team: 'チーム', mp: 'マッチポイント', gp: 'ゲームポイント', upsets: 'レーティング差の番狂わせ', winner: '勝ち', loser: '負け', difference: '差', games: '対局数', whiteWins: '白の勝ち', blackWins: '黒の勝ち', draws: '引き分け', inNumbers: '数字で見る', longest: '最長の対局', openings: 'よく指されたオープニング', moves: '手', rounds: 'ラウンドごと', stories: '一手ずつ見る対局', counted: '公式中継の対局から集計しています。4ボードすべてが中継された対戦のみを数えます。マッチポイントが同じチームはここではゲームポイント順で、公式の順位は大会のタイブレークで決まります。', official: '公式順位', site: '公式サイト', broadcast: 'Lichessの公式中継' },
  ko: { section: '체스 올림피아드', topMatches: '상위 대진', standings: '순위', team: '팀', mp: '매치 포인트', gp: '게임 포인트', upsets: '레이팅 이변', winner: '승', loser: '패', difference: '차이', games: '대국', whiteWins: '백 승', blackWins: '흑 승', draws: '무승부', inNumbers: '숫자로 보기', longest: '가장 긴 대국', openings: '가장 많이 둔 오프닝', moves: '수', rounds: '라운드별', stories: '한 수씩 보는 대국', counted: '공식 중계의 대국으로 집계했습니다. 네 보드가 모두 중계된 대진만 셉니다. 매치 포인트가 같은 팀은 여기서 게임 포인트 순이며, 공식 순위는 대회의 타이브레이크로 정해집니다.', official: '공식 순위', site: '공식 사이트', broadcast: 'Lichess 공식 중계' },
  'zh-hans': { section: '国际象棋奥林匹克', topMatches: '前台对阵', standings: '积分榜', team: '队伍', mp: '团体分', gp: '局分', upsets: '按等级分的爆冷', winner: '胜', loser: '负', difference: '差距', games: '对局', whiteWins: '白方胜', blackWins: '黑方胜', draws: '和棋', inNumbers: '数据', longest: '最长的对局', openings: '最常见的开局', moves: '回合', rounds: '逐轮', stories: '对局，一步一步', counted: '根据官方直播的对局统计：只有四个台次都被直播的对阵才计入。团体分相同的队伍此处按局分排列；正式名次以赛事的对比分为准。', official: '官方积分榜', site: '官方网站', broadcast: 'Lichess上的官方直播' },
  'zh-hant': { section: '西洋棋奧林匹克', topMatches: '前台對陣', standings: '積分榜', team: '隊伍', mp: '團體分', gp: '局分', upsets: '按等級分的爆冷', winner: '勝', loser: '負', difference: '差距', games: '對局', whiteWins: '白方勝', blackWins: '黑方勝', draws: '和棋', inNumbers: '數據', longest: '最長的對局', openings: '最常見的開局', moves: '回合', rounds: '逐輪', stories: '對局，一步一步', counted: '根據官方直播的對局統計：只有四個台次都被直播的對陣才計入。團體分相同的隊伍此處按局分排列；正式名次以賽事的對比分為準。', official: '官方積分榜', site: '官方網站', broadcast: 'Lichess上的官方直播' },
  th: { section: 'หมากรุกโอลิมปิก', topMatches: 'แมตช์หัวแถว', standings: 'ตารางคะแนน', team: 'ทีม', mp: 'แต้มแมตช์', gp: 'แต้มกระดาน', upsets: 'พลิกล็อกตามเรตติ้ง', winner: 'ชนะ', loser: 'แพ้', difference: 'ส่วนต่าง', games: 'เกม', whiteWins: 'ฝ่ายขาวชนะ', blackWins: 'ฝ่ายดำชนะ', draws: 'เสมอ', inNumbers: 'ตัวเลข', longest: 'เกมที่ยาวที่สุด', openings: 'การเปิดเกมที่เล่นมากที่สุด', moves: 'ตา', rounds: 'ทีละรอบ', stories: 'เกม ทีละตา', counted: 'นับจากเกมในการถ่ายทอดอย่างเป็นทางการ แมตช์จะนับเมื่อถ่ายทอดครบทั้งสี่กระดาน ทีมที่แต้มแมตช์เท่ากันเรียงตามแต้มกระดานที่นี่ ลำดับอย่างเป็นทางการใช้เกณฑ์ตัดสินของรายการ', official: 'ตารางคะแนนอย่างเป็นทางการ', site: 'เว็บไซต์อย่างเป็นทางการ', broadcast: 'การถ่ายทอดอย่างเป็นทางการบน Lichess' },
  vi: { section: 'Olympiad Cờ vua', topMatches: 'Các trận đầu bảng', standings: 'Bảng xếp hạng', team: 'Đội', mp: 'Điểm trận', gp: 'Điểm ván', upsets: 'Bất ngờ theo Elo', winner: 'Thắng', loser: 'Thua', difference: 'Chênh lệch', games: 'Ván đấu', whiteWins: 'Trắng thắng', blackWins: 'Đen thắng', draws: 'Hòa', inNumbers: 'Qua các con số', longest: 'Ván dài nhất', openings: 'Khai cuộc được chơi nhiều nhất', moves: 'nước', rounds: 'Từng vòng', stories: 'Các ván đấu, từng nước', counted: 'Tính từ các ván của buổi phát sóng chính thức: một trận được tính khi cả bốn bàn đều được phát sóng. Các đội bằng điểm trận được xếp ở đây theo điểm ván; thứ tự chính thức dùng các chỉ số phụ của giải.', official: 'Bảng xếp hạng chính thức', site: 'Trang chính thức', broadcast: 'Buổi phát sóng chính thức trên Lichess' },
  id: { section: 'Olimpiade Catur', topMatches: 'Pertandingan teratas', standings: 'Klasemen', team: 'Tim', mp: 'Poin pertandingan', gp: 'Poin partai', upsets: 'Kejutan menurut rating', winner: 'Menang', loser: 'Kalah', difference: 'Selisih', games: 'Partai', whiteWins: 'Putih menang', blackWins: 'Hitam menang', draws: 'Remis', inNumbers: 'Dalam angka', longest: 'Partai terpanjang', openings: 'Pembukaan yang paling sering dimainkan', moves: 'langkah', rounds: 'Babak demi babak', stories: 'Partai-partai, langkah demi langkah', counted: 'Dihitung dari partai-partai siaran resmi: sebuah pertandingan dihitung bila keempat papannya disiarkan. Tim dengan poin pertandingan yang sama diurutkan di sini menurut poin partai; urutan resmi memakai tiebreak turnamen.', official: 'Klasemen resmi', site: 'Situs resmi', broadcast: 'Siaran resmi di Lichess' },
  ms: { section: 'Olimpiad Catur', topMatches: 'Perlawanan teratas', standings: 'Kedudukan', team: 'Pasukan', mp: 'Mata perlawanan', gp: 'Mata permainan', upsets: 'Kejutan mengikut penarafan', winner: 'Menang', loser: 'Kalah', difference: 'Beza', games: 'Permainan', whiteWins: 'Putih menang', blackWins: 'Hitam menang', draws: 'Seri', inNumbers: 'Dalam angka', longest: 'Permainan terpanjang', openings: 'Pembukaan paling kerap dimainkan', moves: 'langkah', rounds: 'Pusingan demi pusingan', stories: 'Permainan, langkah demi langkah', counted: 'Dikira daripada permainan siaran rasmi: sesuatu perlawanan dikira apabila keempat-empat papannya disiarkan. Pasukan yang sama mata perlawanan disusun di sini mengikut mata permainan; susunan rasmi menggunakan pemecah seri kejohanan.', official: 'Kedudukan rasmi', site: 'Laman rasmi', broadcast: 'Siaran rasmi di Lichess' },
  ro: { section: 'Olimpiada de Șah', topMatches: 'Meciurile de vârf', standings: 'Clasamentul', team: 'Echipa', mp: 'Puncte de meci', gp: 'Puncte de partidă', upsets: 'Surprize după rating', winner: 'A câștigat', loser: 'A pierdut', difference: 'Diferență', games: 'Partide', whiteWins: 'Victorii ale albului', blackWins: 'Victorii ale negrului', draws: 'Remize', inNumbers: 'În cifre', longest: 'Cea mai lungă partidă', openings: 'Cele mai jucate deschideri', moves: 'mutări', rounds: 'Rundă cu rundă', stories: 'Partidele, mutare cu mutare', counted: 'Numărat din partidele transmisiei oficiale: un meci contează când toate cele patru mese au fost transmise. Echipele la egalitate de puncte de meci sunt ordonate aici după punctele de partidă; ordinea oficială folosește departajările turneului.', official: 'Clasamentul oficial', site: 'Site oficial', broadcast: 'Transmisia oficială pe Lichess' },
};

export function reportWords(slug: string): ReportWords {
  return REPORT_WORDS[slug] ?? REPORT_WORDS[slug.split('-')[0]] ?? en;
}
