#!/usr/bin/env node
// The website's copy of the feed, from the feed itself.
//
//   node scripts/feed/site.mjs            the feed as it is
//   node scripts/feed/site.mjs --empty    no stories, for a build without the network
//
// The site carries exactly what the feed's public files carry — which the
// collector's FEED_PUBLIC decides, for the app and the site at once: every
// story while the feature is tested, only approved ones after. One switch, so
// the site can never show a story the app does not, or the other way round.
//
// Reads the public files through brasspawn.com, as any visitor would, and
// writes them as TypeScript modules the bundler can split: one small index
// that lists every story, and one module per story that only its own page
// loads. web/scripts/deploy.sh runs it before every build, so the pages a
// crawler finds are the history as it stood that day; a story newer than the
// last deploy gets its page from the collector, which renders it with this
// build's own renderer — see pages.mjs.
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { forSite, line } from './page-story.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const FEED = process.env.FEED_ORIGIN ?? 'https://brasspawn.com/media/feed/v1';

async function json(path) {
  // A few tries, as the collector's own requests have: a connection that
  // times out once is a network having a moment, not a feed that is gone.
  for (let attempt = 1; ; attempt++) {
    try {
      const response = await fetch(`${FEED}/${path}`, {
        headers: { Accept: 'application/json' },
        signal: AbortSignal.timeout(30_000),
      });
      if (response.status === 404 || response.status === 403) return null;
      if (response.status >= 500 && attempt < 4) throw new Error(`${response.status} for ${path}`);
      if (!response.ok) throw Object.assign(new Error(`${response.status} for ${path}`), { final: true });
      return await response.json();
    } catch (error) {
      if (error.final || attempt >= 4) throw error;
      await new Promise((done) => setTimeout(done, 1500 * attempt));
    }
  }
}

// --empty writes the modules with nothing in them: a build with no network,
// or one that should not carry the feed, still compiles.
const empty = process.argv.includes('--empty');
const latest = empty ? { days: [] } : ((await json('latest.json')) ?? { days: [], stories: [] });
const stories = [];
for (const { date } of latest.days ?? []) {
  const day = await json(`days/${date}.json`);
  for (const story of day?.stories ?? []) stories.push(forSite(story));
}
stories.sort((a, b) => b.date.localeCompare(a.date));

const dir = resolve(ROOT, 'web/src/app/pages/today/feed');
await rm(resolve(dir, 'stories'), { recursive: true, force: true });
await mkdir(resolve(dir, 'stories'), { recursive: true });
const header = '// Generated by scripts/feed/site.mjs from media/feed/v1 — do not edit.\n';
const summary = ({ id, date, headline, lede, event, white, black, result, fen, last }) =>
  ({ id, date, headline, lede, event, white, black, result, fen, last });

for (const story of stories) {
  const { status, ...page } = story;
  page.line = line(story.moves);
  await writeFile(
    resolve(dir, `stories/${story.id}.ts`),
    `${header}import type { Story } from '../types';\n\nexport const story: Story = ${JSON.stringify(page, null, 2)};\n`,
  );
}
await writeFile(
  resolve(dir, 'index.ts'),
  `${header}import type { StorySummary } from './types';\n\n` +
    `export const FEED: readonly StorySummary[] = ${JSON.stringify(stories.map(summary), null, 2)};\n`,
);
await writeFile(
  resolve(dir, 'stories.ts'),
  `${header}import type { Story } from './types';\n\nexport const STORIES: Record<string, () => Promise<Story>> = {\n` +
    stories.map((s) => `  '${s.id}': () => import('./stories/${s.id}').then((m) => m.story),`).join('\n') +
    `\n};\n`,
);
// For the sitemap, which is written by a plain Node script after the build.
await writeFile(resolve(dir, 'sitemap.json'), JSON.stringify(stories.map(({ id, date }) => ({ id, date }))) + '\n');

// Each language's list, from that language's copy of the feed: the same
// stories, their headlines and ledes in the language — for /de/today and the
// rest. The story pages themselves are the collector's (pages.mjs); the lists
// are prerendered here, one small module per language, loaded by its page.
const FOLDERS = {
  ar: 'ar', bg: 'bg', cs: 'cs', da: 'da', de: 'de', el: 'el', es: 'es', fi: 'fi', fr: 'fr', he: 'he',
  hi: 'hi', hu: 'hu', id: 'id', it: 'it', ja: 'ja', ko: 'ko', ms: 'ms', nl: 'nl', no: 'no', pl: 'pl',
  'pt-br': 'pt-BR', ro: 'ro', ru: 'ru', sv: 'sv', th: 'th', tr: 'tr', vi: 'vi', 'zh-hans': 'zh-Hans', 'zh-hant': 'zh-Hant',
};
await rm(resolve(dir, 'i18n'), { recursive: true, force: true });
await mkdir(resolve(dir, 'i18n'), { recursive: true });
const jobs = Object.entries(FOLDERS).flatMap(([slug, folder]) => (latest.days ?? []).map(({ date }) => ({ slug, folder, date })));
const byLanguage = Object.fromEntries(Object.keys(FOLDERS).map((slug) => [slug, new Map()]));
// Sixteen at a time: the files are small, and the edge has them.
for (let i = 0; i < jobs.length; i += 16) {
  await Promise.all(jobs.slice(i, i + 16).map(async ({ slug, folder, date }) => {
    const day = await json(`${folder}/days/${date}.json`);
    for (const story of day?.stories ?? []) byLanguage[slug].set(story.id, story);
  }));
}
for (const [slug, found] of Object.entries(byLanguage)) {
  // The English list's order, the language's words; a story the language's
  // copy does not have yet is listed in English.
  const list = stories.map((story) => {
    const own = found.get(story.id);
    return summary(own ? { ...story, headline: own.headline, lede: own.lede ?? story.lede } : story);
  });
  await writeFile(
    resolve(dir, `i18n/${slug}.ts`),
    `${header}import type { StorySummary } from '../types';\n\nexport const FEED: readonly StorySummary[] = ${JSON.stringify(list, null, 2)};\n`,
  );
}
await writeFile(
  resolve(dir, 'i18n/index.ts'),
  `${header}import type { StorySummary } from '../types';\n\nexport const LOCAL_FEEDS: Record<string, () => Promise<readonly StorySummary[]>> = {\n` +
    Object.keys(FOLDERS).map((slug) => `  '${slug}': () => import('./${slug}').then((m) => m.FEED),`).join('\n') +
    `\n};\n`,
);

// The Olympiad's reports, for the list's link to them: the event's and the
// latest round's, in each language — read from each language's index of them
// (reports.mjs). The list asks the live index for newer ones in the browser.
const links = {};
const reportIndex = async (folder) => (empty ? null : await json(`${folder ? `${folder}/` : ''}reports/index.json`));
const pick = (index) => {
  const reports = index?.reports ?? [];
  return [reports.find((r) => r.kind === 'event'), reports.find((r) => r.kind === 'round')]
    .filter(Boolean)
    .map(({ id, kind, round, headline }) => ({ id, kind, round, headline }));
};
links.en = pick(await reportIndex(null));
await Promise.all(Object.entries(FOLDERS).map(async ([slug, folder]) => (links[slug] = pick(await reportIndex(folder)))));
await writeFile(
  resolve(dir, 'reports.ts'),
  `${header}import type { ReportLink } from './types';\n\nexport const REPORT_LINKS: Record<string, readonly ReportLink[]> = ${JSON.stringify(links, null, 2)};\n`,
);
console.error(`${stories.length} stories → web/src/app/pages/today/feed, in ${Object.keys(FOLDERS).length + 1} languages; ${links.en.length} report links`);
