#!/usr/bin/env node
// The website's copy of the feed, from the feed itself.
//
//   node scripts/feed/site.mjs            the feed as it is
//   node scripts/feed/site.mjs --empty    no stories, for a build without the network
//
// The site carries exactly what the feed's public files carry — which the
// collector's FEED_PUBLIC decides, for the app and the site at once: every
// story while the feature is tested, only approved ones after. One switch, so
// the site can never show a story the app does not, or the other way round.
//
// Reads the public files through brasspawn.com, as any visitor would, and
// writes them as TypeScript modules the bundler can split: one small index
// that lists every story, and one module per story that only its own page
// loads. web/scripts/deploy.sh runs it before every build, so the pages a
// crawler finds are the history as it stood that day; stories newer than the
// last deploy are shown by /today/story from the same files, in the browser.
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Chess } from 'chess.js';

import { positionAt } from './diagram.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const FEED = process.env.FEED_ORIGIN ?? 'https://brasspawn.com/media/feed/v1';

async function json(path) {
  const response = await fetch(`${FEED}/${path}`, { headers: { Accept: 'application/json' } });
  if (response.status === 404 || response.status === 403) return null;
  if (!response.ok) throw new Error(`${response.status} for ${path}`);
  return response.json();
}

/** A story as the site reads it — the stored story, with the board worked out if it is not. */
function forSite(story) {
  const sans = story.moves.split(' ');
  const board = story.fen ? { fen: story.fen, last: story.last ?? null } : positionAt(sans, story.key?.ply ?? sans.length);
  return {
    id: story.id,
    status: story.status,
    date: story.date,
    headline: story.headline,
    lede: story.lede ?? story.body.split(/(?<=[.!?])\s+(?=[A-Z0-9])/)[0],
    event: story.event,
    white: story.white,
    black: story.black,
    result: story.result,
    fen: board.fen,
    last: board.last,
    opening: story.opening,
    moves: story.moves,
    key: story.key,
    body: story.body,
    url: story.url,
    source: story.source,
  };
}

// --empty writes the modules with nothing in them: a build with no network,
// or one that should not carry the feed, still compiles.
const empty = process.argv.includes('--empty');
const latest = empty ? { days: [] } : ((await json('latest.json')) ?? { days: [], stories: [] });
const stories = [];
for (const { date } of latest.days ?? []) {
  const day = await json(`days/${date}.json`);
  for (const story of day?.stories ?? []) stories.push(forSite(story));
}
stories.sort((a, b) => b.date.localeCompare(a.date));

const dir = resolve(ROOT, 'web/src/app/pages/today/feed');
await rm(resolve(dir, 'stories'), { recursive: true, force: true });
await mkdir(resolve(dir, 'stories'), { recursive: true });
const header = '// Generated by scripts/feed/site.mjs from media/feed/v1 — do not edit.\n';
const summary = ({ id, date, headline, lede, event, white, black, result, fen, last }) =>
  ({ id, date, headline, lede, event, white, black, result, fen, last });

/**
 * Every position of the game and the move that made it, for the story page's
 * replay. Worked out here so the site ships no chess rules: a page steps
 * through a list of boards it was handed. A few kilobytes a story, and only
 * in the story's own module — never in the list.
 */
function line(moves) {
  const chess = new Chess();
  const out = [{ fen: chess.fen(), last: null }];
  for (const san of moves.split(' ')) {
    const move = chess.move(san);
    out.push({ fen: chess.fen().split(' ')[0], last: { from: move.from, to: move.to } });
  }
  return out;
}

for (const story of stories) {
  const { status, ...page } = story;
  page.line = line(story.moves);
  await writeFile(
    resolve(dir, `stories/${story.id}.ts`),
    `${header}import type { Story } from '../types';\n\nexport const story: Story = ${JSON.stringify(page, null, 2)};\n`,
  );
}
await writeFile(
  resolve(dir, 'index.ts'),
  `${header}import type { StorySummary } from './types';\n\n` +
    `export const FEED: readonly StorySummary[] = ${JSON.stringify(stories.map(summary), null, 2)};\n`,
);
await writeFile(
  resolve(dir, 'stories.ts'),
  `${header}import type { Story } from './types';\n\nexport const STORIES: Record<string, () => Promise<Story>> = {\n` +
    stories.map((s) => `  '${s.id}': () => import('./stories/${s.id}').then((m) => m.story),`).join('\n') +
    `\n};\n`,
);
// For the sitemap, which is written by a plain Node script after the build.
await writeFile(resolve(dir, 'sitemap.json'), JSON.stringify(stories.map(({ id, date }) => ({ id, date }))) + '\n');
console.error(`${stories.length} stories → web/src/app/pages/today/feed`);
