// Arabic (ar-SA). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'العب · تدرّب · شاهد',
    lede: 'تكتيك، وتقييم للأوضاع، وتقنية نهايات، ومباريات مع تدريب — ومحرّك المحرك يعمل على الجهاز نفسه. لا شيء يغادر الهاتف.',
    privacy:
      'لا يجمع التطبيق شيئًا، ولا يرسل شيئًا، ولا يجري أي اتصال بالشبكة. تصنيفاتك وسجلّك محفوظة على هذا الجهاز وحده، وتُحذف بحذف التطبيق.',
    freeSoftware:
      'هذا التطبيق برمجية حرّة، مرخّصة برخصة GNU General Public License الإصدار 3 أو أحدث.',
    stockfish:
      'يتضمّن التطبيق محرّك Stockfish المنشور برخصة GPLv3. ولأن Stockfish مرتبط بالتطبيق، يخضع التطبيق كله للرخصة نفسها، وشيفرته المصدرية كاملةً منشورة.',
    reckless:
      'يتضمن التطبيق أيضًا Reckless، وهو محرك ثانٍ مرخّص بـ AGPLv3. الرخصتان تتوافقان، وبند Affero الخاص بالبرمجيات المستخدمة عبر الشبكة لا يغيّر شيئًا هنا: كلا المحركين يعملان على هذا الجهاز، والتطبيق لا يجري أي طلبات شبكية.',
    coaching: 'يُقيّم المدرب كل نقلة تلعبها فور لعبها.',
    online: 'خصم حقيقي عبر Game Center، مع ساعة. بلا تلميحات، بلا محرّك، وبلا تراجع عن النقلات.',
    photo: 'اقرأ لوحاً من صورة',
    takeOver: 'واصل اللعب من هنا',
    freeForever:
      'اللعب يبقى مجانًا — أمام المحرّك وأمام الناس، بلا حدود وبلا إعلانات. ما يفتحه Pro هو التدريب.',
    allowance:
      'تُعاد الحصة كل يوم في الساعة 9 صباحًا بالتوقيت المحلي. اللعب — أمام المحرّك أو أمام شخص — بلا حدود ولا يحتاج شيئًا.',
    noAds: 'لا إعلانات في أي جزء من التطبيق، أبدًا',
    unlimitedPuzzles: 'كل الألغاز الـ14351، بأي عدد تريده في اليوم',
    unlimitedRush: 'جولات سريعة بلا حدّ يومي',
    unlimitedRest: 'تقييم الأوضاع وتمارين النهايات وتخمين التصنيف، بلا حدود',
    renewal:
      'تتجدّد الخطة الشهرية كل شهر حتى تُلغيها. يمكنك الإلغاء في أي وقت من الإعدادات › حساب Apple › الاشتراكات، قبل يوم واحد على الأقل من التجديد. الفتح لمرة واحدة دفعة واحدة ولا يتجدّد أبدًا.',
    pro: 'Brass Pawn Pro',
    monthly: 'شهريًا',
    lifetime: 'فتح لمرة واحدة',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfUse: 'شروط الاستخدام',
    licence: 'الرخصة',
    credits: 'المساهمون',
  },
  modes: {
    play: 'اللعب',
    watch: 'مشاهدة',
    tactics: 'التكتيك',
    positional: 'الوضعي',
    endgames: 'النهايات',
    guess: 'خمّن التصنيف',
    online: 'على الإنترنت',
    progress: 'التقدّم',
    rush: 'جولة سريعة',
  },
  shots: {
    title: ['كل نقلة تلعبها،', 'تُقرأ لك.'],
    mistake: ['لا يكتفي بإخبارك', 'أنك خسرت.'],
    values: ['قيمة كل نقلة.', 'قبل أن تلعبها.'],
    library: ['تسعمئة مباراة', 'تستحق المشاهدة.'],
    engines: ['محرّكان.', 'رأي ثانٍ.'],
    coached: ['وحين تصيب،', 'يقولها لك.'],
    free: ['خمسة من كل شيء،', 'مجانًا.'],
  },
  spoken: {
    watch:
      'تسعمئة مباراة تستحق المشاهدة. ابحث عن واحدة وتابعها — وعند أول نقلة كنت ستلعبها بشكل مختلف، تولَّ أنت.',
    tactics: 'أربعة عشر ألف لغز، مختارة مما تخطئ فيه دائمًا. ثم اعرف قيمة كل نقلة — قبل أن تلعبها.',
    play: 'أسرع طريقة لتتحسّن في الشطرنج؟ أن تعرف لماذا نجحت كل نقلة. Brass Pawn يخبرك — نقلة بنقلة.',
  },
  ui: {
    category: 'مدرّب شطرنج لـ iPhone و iPad',
    support: 'الدعم',
    language: 'اللغة',
    menu: 'القائمة',
    close: 'إغلاق',
    skip: 'تخطَّ إلى المحتوى',
    inEnglish: 'بالإنجليزية',
    film: 'شاهده وهو يعمل',
    screens: 'كل شاشة',
    price: 'الأسعار',
    questions: 'أسئلة',
    narrated: 'مع التعليق',
    silent: 'بلا صوت',
    play: 'تشغيل',
    pause: 'إيقاف مؤقت',
    download: 'التنزيل من App Store',
    soon: 'قريبًا على App Store',
    more: 'المزيد عن التطبيق',
    free: 'مجانًا كل يوم',
    faq: [
      'هل يحتاج إلى اتصال بالإنترنت؟',
      'ما المجاني فيه؟',
      'كيف يعمل الاشتراك؟',
      'هل يمكنني الاطلاع على الشيفرة المصدرية؟',
    ],
    prices: 'الأسعار المعروضة هي أسعار App Store الأمريكي، وسعرك المحلي يحدده App Store.',
  },
};
