// Czech (cs). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Hraj · Trénuj · Sleduj',
    lede: 'Taktika, poziční úsudek, koncovková technika a partie s koučem, se engineem běžícím přímo v zařízení. Nic neopouští telefon.',
    privacy:
      'Aplikace nic nesbírá, nic neodesílá a nedělá žádné síťové požadavky. Tvoje ratingy a historie zůstávají jen v tomto zařízení a smažou se spolu s aplikací.',
    freeSoftware:
      'Tato aplikace je svobodný software pod licencí GNU General Public License verze 3 nebo novější.',
    stockfish:
      'Aplikace obsahuje Stockfish, který je pod licencí GPLv3. Protože je Stockfish do aplikace slinkován, podléhá stejné licenci celá aplikace — a její úplný zdrojový kód je zveřejněn.',
    reckless:
      'Obsahuje také Reckless, druhý engine, pod licencí AGPLv3. Obě licence lze spojit a klauzule Affero o softwaru používaném přes síť zde nic nemění: oba enginy běží na tomto zařízení a aplikace neprovádí žádné síťové požadavky.',
    coaching: 'Trenér hodnotí každý váš tah hned, jak jej zahrajete.',
    online:
      'Skutečný soupeř přes Game Center, na hodiny. Bez nápověd, bez enginu, bez braní tahů zpět.',
    photo: 'Načíst šachovnici z fotky',
    takeOver: 'Hrát dál odsud',
    freeForever:
      'Hraní zůstává zdarma — proti enginu i proti lidem, bez omezení a bez reklam. Pro odemyká trénink.',
    allowance:
      'Limit se obnoví každý den v 9:00 místního času. Hraní — proti enginu i proti člověku — je bez omezení a zdarma.',
    noAds: 'Žádné reklamy, nikde v aplikaci, nikdy',
    unlimitedPuzzles: 'Všech 14 351 úloh, kolik denně chceš',
    unlimitedRush: 'Série Rush bez denního limitu',
    unlimitedRest: 'Poziční úsudek, koncovky a Hádej Elo bez omezení',
    renewal:
      'Měsíční plán se obnovuje každý měsíc, dokud ho nezrušíš. Zrušit můžeš kdykoli v Nastavení › Účet Apple › Předplatná, nejpozději den před obnovením. Jednorázové odemčení je jediná platba a nikdy se neobnovuje.',
    pro: 'Brass Pawn Pro',
    monthly: 'Měsíčně',
    lifetime: 'Jednorázově',
    privacyPolicy: 'Zásady ochrany soukromí',
    termsOfUse: 'Podmínky použití',
    licence: 'Licence',
    credits: 'Autoři',
  },
  modes: {
    play: 'Hra',
    watch: 'Sledovat',
    tactics: 'Taktika',
    positional: 'Poziční',
    endgames: 'Koncovky',
    guess: 'Hádej Elo',
    online: 'Online',
    progress: 'Pokrok',
    rush: 'Rush',
  },
  shots: {
    title: ['Každý tvůj tah,', 'přečtený nahlas.'],
    mistake: ['Neřekne ti jen,', 'že jsi prohrál.'],
    values: ['Co který tah stojí.', 'Ještě než ho zahraješ.'],
    library: ['Devět set partií,', 'které stojí za sledování.'],
    engines: ['Dva enginy.', 'Druhý názor.'],
    coached: ['A když se trefíš,', 'řekne to.'],
    free: ['Pět od všeho,', 'zdarma.'],
  },
  spoken: {
    watch:
      'Devět set partií, které stojí za sledování. Najdi si jednu — a ve chvíli, kdy bys táhl jinak, převezmi ji.',
    tactics:
      'Čtrnáct tisíc úloh, vybraných z toho, co ti nejde. A pak uvidíš, co který tah stojí — ještě než ho zahraješ.',
    play: 'Nejrychlejší způsob, jak se zlepšit v šachu? Vědět, proč každý tah fungoval. Brass Pawn ti to řekne — tah za tahem.',
  },
  ui: {
    category: 'šachový trenér pro iPhone a iPad',
    support: 'Podpora',
    language: 'Jazyk',
    menu: 'Nabídka',
    close: 'Zavřít',
    film: 'Podívej se, jak to chodí',
    screens: 'Každá obrazovka',
    price: 'Kolik to stojí',
    questions: 'Otázky',
    narrated: 'S komentářem',
    silent: 'Bez zvuku',
    play: 'Přehrát',
    pause: 'Pozastavit',
    download: 'Stáhnout v App Store',
    soon: 'Brzy v App Store',
    more: 'Více o aplikaci',
    free: 'Zdarma každý den',
    faq: [
      'Potřebuje připojení k internetu?',
      'Co je zdarma?',
      'Jak funguje předplatné?',
      'Můžu se podívat na zdrojový kód?',
    ],
    prices: 'Uvedené ceny jsou z amerického App Storu. Tvoji místní cenu určuje App Store.',
  },
};
