// Danish (da). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Spil · Træn · Se',
    lede: 'Taktik, positionsvurdering, slutspilsteknik og partier med coaching, med motoren kørende på selve enheden. Intet forlader telefonen.',
    privacy:
      'Appen indsamler intet, sender intet og laver ingen netværkskald. Dine ratings og din historik ligger kun på denne enhed og slettes sammen med appen.',
    freeSoftware:
      'Denne app er fri software, licenseret under GNU General Public License version 3 eller nyere.',
    stockfish:
      'Appen indeholder Stockfish, som er udgivet under GPLv3. Fordi Stockfish er linket ind i appen, er hele appen omfattet af samme licens — og dens fulde kildekode er offentliggjort.',
    reckless:
      'Appen indeholder også Reckless, en anden motor, under AGPLv3. De to licenser kan kombineres, og Affero-klausulen om software der bruges over et netværk ændrer intet her: begge motorer kører på denne enhed, og appen laver ingen netværkskald.',
    coaching: 'Træneren bedømmer hvert af dine træk, efterhånden som du spiller dem.',
    online:
      'En rigtig modstander via Game Center, på ur. Ingen hints, ingen motor, ingen fortrydelser.',
    photo: 'Læs et bræt fra et foto',
    takeOver: 'Spil videre herfra',
    freeForever:
      'At spille er stadig gratis — mod motoren og mod mennesker, uden grænser og uden reklamer. Det Pro låser op for, er træningen.',
    allowance:
      'Kvoten nulstilles hver dag kl. 9.00 lokal tid. At spille — mod motoren eller mod et menneske — er uden grænser og gratis.',
    noAds: 'Ingen reklamer, ingen steder i appen, aldrig',
    unlimitedPuzzles: 'Alle 14.351 opgaver, så mange om dagen du vil',
    unlimitedRush: 'Rush-runder uden daglig grænse',
    unlimitedRest: 'Positionsvurdering, slutspilsøvelser og Gæt ratingen, uden grænser',
    renewal:
      'Månedsabonnementet fornyes hver måned, indtil du opsiger det. Du kan opsige når som helst i Indstillinger › Apple-konto › Abonnementer, senest en dag før fornyelsen. Engangskøbet er en enkelt betaling og fornyes aldrig.',
    pro: 'Brass Pawn Pro',
    monthly: 'Månedligt',
    lifetime: 'Engangskøb',
    privacyPolicy: 'Privatlivspolitik',
    termsOfUse: 'Vilkår for brug',
    licence: 'Licens',
    credits: 'Medvirkende',
  },
  modes: {
    play: 'Spil',
    watch: 'Se',
    tactics: 'Taktik',
    positional: 'Position',
    endgames: 'Slutspil',
    guess: 'Gæt ratingen',
    online: 'Online',
    progress: 'Fremgang',
    rush: 'Rush',
  },
  shots: {
    title: ['Hvert træk du gør,', 'læst tilbage til dig.'],
    mistake: ['Den siger ikke bare,', 'at du tabte.'],
    values: ['Hvad hvert træk er værd.', 'Før du trækker.'],
    library: ['Ni hundrede partier', 'værd at se.'],
    engines: ['To motorer.', 'En anden mening.'],
    coached: ['Og når du rammer rigtigt,', 'siger den det.'],
    free: ['Fem af hver slags,', 'gratis.'],
  },
  spoken: {
    watch:
      'Ni hundrede partier værd at se. Find et, følg det — og i det øjeblik du ville have trukket anderledes, så overtag.',
    tactics:
      'Fjorten tusind opgaver, valgt ud fra det du bliver ved med at ramme forkert. Og se hvad hvert træk er værd — før du trækker.',
    play: 'Den hurtigste vej til bedre skak? At vide hvorfor hvert træk virkede. Brass Pawn fortæller dig det — træk for træk.',
  },
  ui: {
    category: 'en skaktræner til iPhone og iPad',
    support: 'Support',
    language: 'Sprog',
    menu: 'Menu',
    close: 'Luk',
    film: 'Se den i brug',
    screens: 'Hver skærm',
    price: 'Hvad det koster',
    questions: 'Spørgsmål',
    narrated: 'Med fortæller',
    silent: 'Uden lyd',
    play: 'Afspil',
    pause: 'Pause',
    download: 'Hent i App Store',
    soon: 'Snart i App Store',
    more: 'Mere om appen',
    free: 'Gratis hver dag',
    faq: [
      'Kræver den internetforbindelse?',
      'Hvad er gratis?',
      'Hvordan fungerer abonnementet?',
      'Kan jeg se kildekoden?',
    ],
    prices:
      'De viste priser er fra det amerikanske App Store. Din lokale pris fastsættes af App Store.',
  },
};
