// German (de-DE). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Spielen · Trainieren · Zusehen',
    lede: 'Taktik, Stellungsbeurteilung, Endspieltechnik und begleitetes Spiel, mit der Engine direkt auf dem Gerät. Nichts verlässt das Telefon.',
    privacy:
      'Die App sammelt nichts, sendet nichts und stellt keine Netzwerkanfragen. Deine Wertungen und deine Historie liegen nur auf diesem Gerät; wer die App löscht, löscht sie mit.',
    freeSoftware:
      'Diese Anwendung ist freie Software unter der GNU General Public License Version 3 oder später.',
    stockfish:
      'Die App enthält Stockfish, das unter der GPLv3 steht. Weil Stockfish in die App eingebunden ist, gilt dieselbe Lizenz für die gesamte Anwendung — und ihr vollständiger Quelltext ist veröffentlicht.',
    reckless:
      'Sie enthält außerdem Reckless, eine zweite Engine, die unter der AGPLv3 steht. Die beiden Lizenzen lassen sich verbinden, und die Affero-Klausel über Software, die über ein Netzwerk genutzt wird, ändert hier nichts: Beide Engines laufen auf diesem Gerät, und die App stellt keine Netzwerkanfragen.',
    coaching: 'Der Trainer bewertet jeden deiner Züge, sobald du ihn machst.',
    online:
      'Ein echter Gegner über Game Center, mit Uhr. Keine Tipps, keine Engine, keine Zugrücknahme.',
    photo: 'Ein Brett von einem Foto lesen',
    takeOver: 'Von hier aus weiterspielen',
    freeForever:
      'Spielen bleibt kostenlos — gegen die Engine wie gegen Menschen, ohne Grenze und ohne Werbung. Pro schaltet das Training frei.',
    allowance:
      'Das Kontingent wird jeden Tag um 9:00 Uhr Ortszeit zurückgesetzt. Spielen — gegen die Engine oder gegen einen Menschen — ist unbegrenzt und kostet nichts.',
    noAds: 'Keine Werbung, nirgendwo in der App, nie',
    unlimitedPuzzles: 'Alle 14.351 Aufgaben, so viele pro Tag wie du willst',
    unlimitedRush: 'Rush-Läufe ohne Tageslimit',
    unlimitedRest: 'Stellungsbeurteilung, Endspielübungen und Elo raten, unbegrenzt',
    renewal:
      'Das Monatsabo verlängert sich jeden Monat, bis du kündigst. Kündigen kannst du jederzeit unter Einstellungen › Apple-Account › Abonnements, spätestens einen Tag vor der Verlängerung. Die einmalige Freischaltung ist eine einzelne Zahlung und verlängert sich nie.',
    pro: 'Brass Pawn Pro',
    monthly: 'Monatlich',
    lifetime: 'Einmalig freischalten',
    privacyPolicy: 'Datenschutz',
    termsOfUse: 'Nutzungsbedingungen',
    licence: 'Lizenz',
    credits: 'Mitwirkende',
  },
  modes: {
    play: 'Spielen',
    watch: 'Ansehen',
    tactics: 'Taktik',
    positional: 'Stellung',
    endgames: 'Endspiele',
    guess: 'Elo raten',
    online: 'Online',
    progress: 'Fortschritt',
    rush: 'Rush',
  },
  shots: {
    title: ['Jeder Zug, den du machst,', 'dir vorgelesen.'],
    mistake: ['Es sagt nicht nur,', 'dass du verloren hast.'],
    values: ['Was jeder Zug wert ist.', 'Vor dem Zug.'],
    library: ['Neunhundert Partien,', 'die man gesehen haben sollte.'],
    engines: ['Zwei Engines.', 'Eine zweite Meinung.'],
    coached: ['Und wenn du richtig liegst,', 'sagt es das.'],
    free: ['Fünf von allem,', 'kostenlos.'],
  },
  spoken: {
    watch:
      'Neunhundert Partien, die man gesehen haben sollte. Such dir eine — und sobald du anders gezogen hättest, übernimm.',
    tactics:
      'Vierzehntausend Aufgaben, ausgewählt nach dem, was dir schwerfällt. Und dann siehst du, was jeder Zug wert ist — vor dem Zug.',
    play: 'Der schnellste Weg zu besserem Schach? Verstehen, warum ein Zug funktioniert. Brass Pawn sagt es dir — Zug für Zug.',
  },
  ui: {
    category: 'ein Schachtrainer für iPhone und iPad',
    support: 'Support',
    language: 'Sprache',
    menu: 'Menü',
    close: 'Schließen',
    film: 'Sieh es in Bewegung',
    screens: 'Jeder Bildschirm',
    price: 'Was es kostet',
    questions: 'Fragen',
    narrated: 'Mit Kommentar',
    silent: 'Ohne Ton',
    play: 'Abspielen',
    pause: 'Pause',
    download: 'Laden im App Store',
    soon: 'Demnächst im App Store',
    more: 'Mehr über die App',
    free: 'Jeden Tag kostenlos',
    faq: [
      'Braucht die App eine Internetverbindung?',
      'Was ist kostenlos?',
      'Wie funktioniert das Abo?',
      'Kann ich den Quelltext einsehen?',
    ],
    prices:
      'Die angezeigten Preise sind die des US-App-Stores. Deinen lokalen Preis legt der App Store fest.',
  },
};
