// English (en-US). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Play · Train · Watch',
    lede: 'Tactics, positional judgement, endgame technique and coached play, with the engine running on the device. Nothing leaves the phone.',
    privacy:
      'The app collects nothing, sends nothing and makes no network requests. Your ratings and history are stored only on this device, and deleting the app deletes them.',
    freeSoftware:
      'This application is free software, licensed under the GNU Affero General Public License version 3 or later.',
    stockfish:
      'It includes Stockfish, which is GPLv3. Because Stockfish is linked into the app, the whole application carries the same licence — and its complete source is published.',
    reckless:
      'It also includes Reckless, a second engine, which is AGPLv3. The two licences combine, and the Affero clause about software used over a network changes nothing here: both engines run on this device and the app makes no network requests.',
    coaching: 'Coaching grades each of your moves as you make it.',
    online: 'A real opponent over Game Center, on the clock. No hints, no engine, no take-backs.',
    photo: 'Read a board from a photo',
    takeOver: 'Play on from here',
    freeForever:
      'Playing stays free — against the engine and against people, with no limit and no adverts. What Pro unlocks is the training.',
    allowance:
      'The allowance resets every day at 9:00 AM local time. Playing — against the engine or against a person — has no limit and needs nothing.',
    noAds: 'No adverts, in any part of the app, ever',
    unlimitedPuzzles: 'Every one of the 14,351 puzzles, as many a day as you want',
    unlimitedRush: 'Rush runs without a daily limit',
    unlimitedRest: 'Positional judgement, endgame drills and Guess the Elo, unlimited',
    renewal:
      'The monthly plan renews each month until you cancel it. Cancel any time in Settings › Apple Account › Subscriptions, at least a day before it renews. The one-off unlock is a single payment and never renews.',
    pro: 'Brass Pawn Pro',
    monthly: 'Monthly',
    lifetime: 'One-off unlock',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    licence: 'Licence',
    credits: 'Credits',
  },
  modes: {
    play: 'Play',
    watch: 'Watch',
    tactics: 'Tactics',
    positional: 'Positional',
    endgames: 'Endgames',
    guess: 'Guess the Elo',
    online: 'Online',
    progress: 'Progress',
    rush: 'Rush',
  },
  shots: {
    title: ['Every move you play,', 'read back to you.'],
    mistake: ['It does not just say', 'you lost.'],
    values: ['What each move is worth.', 'Before you play it.'],
    library: ['Nine hundred games', 'worth watching.'],
    engines: ['Two engines.', 'A second opinion.'],
    coached: ['And when you get it right,', 'it says so.'],
    free: ['Five of everything,', 'free.'],
  },
  spoken: {
    watch:
      'Nine hundred games worth watching. Find one, follow it — and the moment you would have played differently, take it over.',
    tactics:
      'Fourteen thousand puzzles, picked from what you keep getting wrong. Then see what every move is worth — before you play it.',
    play: 'The fastest way to get better at chess? Know why every move worked. Brass Pawn tells you — every move, every game.',
  },
  ui: {
    category: 'a chess trainer for iPhone and iPad',
    support: 'Support',
    language: 'Language',
    menu: 'Menu',
    close: 'Close',
    film: 'See it in motion',
    screens: 'Every screen',
    price: 'What it costs',
    questions: 'Questions',
    narrated: 'With narration',
    silent: 'Sound off',
    play: 'Play',
    pause: 'Pause',
    download: 'Download on the App Store',
    soon: 'Coming to the App Store',
    more: 'More about the app',
    free: 'Free every day',
    faq: [
      'Does it need an internet connection?',
      'What is free?',
      'How does the subscription work?',
      'Can I see the source code?',
    ],
    prices: 'Prices shown are US App Store prices. Your local price is set by the App Store.',
  },
};
