// Spanish (es-ES). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Juega · Entrena · Observa',
    lede: 'Táctica, criterio posicional, técnica de finales y partidas comentadas, con el motor funcionando en el dispositivo. Nada sale del teléfono.',
    privacy:
      'La aplicación no recoge nada, no envía nada y no hace peticiones de red. Tus valoraciones y tu historial se guardan solo en este dispositivo, y se borran al borrar la aplicación.',
    freeSoftware:
      'Esta aplicación es software libre, con licencia GNU General Public License versión 3 o posterior.',
    stockfish:
      'Incluye Stockfish, que está bajo la GPLv3. Como Stockfish está enlazado en la aplicación, toda la aplicación lleva la misma licencia, y su código fuente completo está publicado.',
    reckless:
      'También incluye Reckless, un segundo motor, bajo licencia AGPLv3. Las dos licencias se combinan, y la cláusula Affero sobre software usado a través de una red no cambia nada aquí: ambos motores se ejecutan en este dispositivo y la app no hace ninguna petición de red.',
    coaching: 'El entrenador califica cada una de tus jugadas en cuanto la haces.',
    online:
      'Un rival de verdad a través de Game Center, con reloj. Sin pistas, sin motor, sin deshacer jugadas.',
    photo: 'Leer un tablero desde una foto',
    takeOver: 'Seguir jugando desde aquí',
    freeForever:
      'Jugar sigue siendo gratis — contra el motor y contra personas, sin límite y sin anuncios. Lo que Pro desbloquea es el entrenamiento.',
    allowance:
      'El cupo se reinicia cada día a las 9:00, hora local. Jugar —contra el motor o contra una persona— no tiene límite y no cuesta nada.',
    noAds: 'Sin anuncios, en ninguna parte de la app, nunca',
    unlimitedPuzzles: 'Los 14.351 ejercicios, tantos al día como quieras',
    unlimitedRush: 'Series de Rush sin límite diario',
    unlimitedRest: 'Criterio posicional, finales y Adivina el Elo, sin límite',
    renewal:
      'El plan mensual se renueva cada mes hasta que lo canceles. Puedes cancelarlo cuando quieras en Ajustes › Cuenta de Apple › Suscripciones, al menos un día antes de la renovación. El pago único es un solo cobro y nunca se renueva.',
    pro: 'Brass Pawn Pro',
    monthly: 'Mensual',
    lifetime: 'Pago único',
    privacyPolicy: 'Política de privacidad',
    termsOfUse: 'Términos de uso',
    licence: 'Licencia',
    credits: 'Créditos',
  },
  modes: {
    play: 'Jugar',
    watch: 'Ver',
    tactics: 'Táctica',
    positional: 'Posicional',
    endgames: 'Finales',
    guess: 'Adivina el Elo',
    online: 'En línea',
    progress: 'Progreso',
    rush: 'Rush',
  },
  shots: {
    title: ['Cada jugada que haces,', 'leída en voz alta.'],
    mistake: ['No solo te dice', 'que perdiste.'],
    values: ['Lo que vale cada jugada.', 'Antes de hacerla.'],
    library: ['Novecientas partidas', 'que merece la pena ver.'],
    engines: ['Dos motores.', 'Una segunda opinión.'],
    coached: ['Y cuando aciertas,', 'te lo dice.'],
    free: ['Cinco de cada,', 'gratis.'],
  },
  spoken: {
    watch:
      'Novecientas partidas que merece la pena ver. Busca una, síguela — y en cuanto habrías jugado distinto, tómala tú.',
    tactics:
      'Catorce mil ejercicios, elegidos según lo que fallas. Y luego ves lo que vale cada jugada — antes de hacerla.',
    play: '¿La forma más rápida de mejorar en ajedrez? Saber por qué funcionó cada jugada. Brass Pawn te lo dice — jugada a jugada.',
  },
  ui: {
    category: 'un entrenador de ajedrez para iPhone y iPad',
    support: 'Soporte',
    language: 'Idioma',
    menu: 'Menú',
    close: 'Cerrar',
    skip: 'Ir al contenido',
    inEnglish: 'en inglés',
    film: 'Míralo en marcha',
    screens: 'Todas las pantallas',
    price: 'Cuánto cuesta',
    questions: 'Preguntas',
    narrated: 'Con narración',
    silent: 'Sin sonido',
    play: 'Reproducir',
    pause: 'Pausa',
    download: 'Consíguelo en el App Store',
    soon: 'Muy pronto en el App Store',
    more: 'Más sobre la app',
    free: 'Gratis cada día',
    faq: [
      '¿Necesita conexión a internet?',
      '¿Qué es gratis?',
      '¿Cómo funciona la suscripción?',
      '¿Puedo ver el código fuente?',
    ],
    prices:
      'Los precios mostrados son los del App Store de EE. UU. Tu precio local lo fija el App Store.',
  },
};
