// Finnish (fi). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Pelaa · Harjoittele · Katso',
    lede: 'Taktiikkaa, aseman arviointia, loppupelitekniikkaa ja valmennettuja pelejä — moottori pyörii itse laitteessa. Mikään ei lähde puhelimesta.',
    privacy:
      'Sovellus ei kerää mitään, ei lähetä mitään eikä tee verkkopyyntöjä. Ratingisi ja historiasi ovat vain tässä laitteessa ja katoavat sovelluksen mukana.',
    freeSoftware:
      'Tämä sovellus on vapaa ohjelmisto, lisensoitu GNU Affero General Public License -lisenssin versiolla 3 tai uudemmalla.',
    stockfish:
      'Sovellus sisältää Stockfishin, joka julkaistaan GPLv3-lisenssillä. Koska Stockfish on linkitetty sovellukseen, koko sovellus on saman lisenssin alainen — ja sen täydellinen lähdekoodi on julkaistu.',
    reckless:
      'Sovellus sisältää myös Recklessin, toisen moottorin, AGPLv3-lisenssillä. Lisenssit sopivat yhteen, eikä Affero-ehto verkon yli käytettävästä ohjelmistosta muuta tässä mitään: molemmat moottorit toimivat tällä laitteella, eikä sovellus tee verkkopyyntöjä.',
    coaching: 'Valmentaja arvioi jokaisen siirtosi heti kun teet sen.',
    online:
      'Oikea vastustaja Game Centerin kautta, kello käynnissä. Ei vihjeitä, ei moottoria, ei siirtojen perumista.',
    photo: 'Lue lauta valokuvasta',
    takeOver: 'Jatka pelaamista tästä',
    freeForever:
      'Pelaaminen pysyy ilmaisena — moottoria ja ihmisiä vastaan, ilman rajaa ja ilman mainoksia. Pro avaa harjoittelun.',
    allowance:
      'Kiintiö nollautuu joka päivä klo 9.00 paikallista aikaa. Pelaaminen — moottoria tai ihmistä vastaan — on rajatonta ja ilmaista.',
    noAds: 'Ei mainoksia missään kohtaa sovellusta, ei koskaan',
    unlimitedPuzzles: 'Kaikki 14 351 tehtävää, niin monta päivässä kuin haluat',
    unlimitedRush: 'Rush-kierroksia ilman päivärajaa',
    unlimitedRest: 'Aseman arviointi, loppupelit ja Arvaa rating — rajatta',
    renewal:
      'Kuukausitilaus uusiutuu joka kuukausi, kunnes peruutat sen. Voit peruuttaa milloin tahansa: Asetukset › Apple-tili › Tilaukset, viimeistään vuorokautta ennen uusiutumista. Kertaosto on yksi maksu eikä uusiudu koskaan.',
    pro: 'Brass Pawn Pro',
    monthly: 'Kuukausittain',
    lifetime: 'Kertaosto',
    privacyPolicy: 'Tietosuojakäytäntö',
    termsOfUse: 'Käyttöehdot',
    licence: 'Lisenssi',
    credits: 'Tekijät',
  },
  modes: {
    play: 'Pelaa',
    watch: 'Katso',
    tactics: 'Taktiikka',
    positional: 'Asema',
    endgames: 'Loppupelit',
    guess: 'Arvaa rating',
    online: 'Verkossa',
    progress: 'Edistyminen',
    rush: 'Rush',
  },
  shots: {
    title: ['Jokainen siirtosi,', 'luettuna ääneen.'],
    mistake: ['Se ei vain kerro,', 'että hävisit.'],
    values: ['Mitä kukin siirto on arvoltaan.', 'Ennen kuin siirrät.'],
    library: ['Yhdeksänsataa peliä,', 'jotka kannattaa katsoa.'],
    engines: ['Kaksi moottoria.', 'Toinen mielipide.'],
    coached: ['Ja kun osut oikeaan,', 'se sanoo sen.'],
    free: ['Viisi kutakin,', 'ilmaiseksi.'],
  },
  spoken: {
    watch:
      'Yhdeksänsataa peliä, jotka kannattaa katsoa. Etsi yksi, seuraa sitä — ja heti kun olisit siirtänyt toisin, jatka itse.',
    tactics:
      'Neljätoista tuhatta tehtävää, valittuna siitä mikä sinulta tökkii. Ja näet mitä kukin siirto on arvoltaan — ennen kuin siirrät.',
    play: 'Nopein tapa kehittyä shakissa? Tietää, miksi jokainen siirto toimi. Brass Pawn kertoo sen — siirto siirrolta.',
  },
  ui: {
    category: 'shakkivalmentaja iPhonelle ja iPadille',
    support: 'Tuki',
    language: 'Kieli',
    menu: 'Valikko',
    close: 'Sulje',
    film: 'Katso se toiminnassa',
    screens: 'Jokainen näkymä',
    price: 'Mitä se maksaa',
    questions: 'Kysymyksiä',
    narrated: 'Kertojan kanssa',
    silent: 'Ilman ääntä',
    play: 'Toista',
    pause: 'Tauko',
    download: 'Lataa App Storesta',
    soon: 'Pian App Storessa',
    more: 'Lisää sovelluksesta',
    free: 'Ilmaiseksi joka päivä',
    faq: [
      'Tarvitaanko internetyhteyttä?',
      'Mikä on ilmaista?',
      'Miten tilaus toimii?',
      'Voinko nähdä lähdekoodin?',
    ],
    prices:
      'Näytetyt hinnat ovat Yhdysvaltain App Storen hintoja. Paikallisen hintasi määrittää App Store.',
  },
};
