// French (Canada) (fr-CA). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: "Jouer · S'entraîner · Regarder",
    lede: "Tactique, jugement positionnel, technique de finale et parties commentées, avec le moteur qui tourne sur l'appareil. Rien ne quitte le téléphone.",
    privacy:
      "L'application ne collecte rien, n'envoie rien et ne fait aucune requête réseau. Vos classements et votre historique restent sur cet appareil, et disparaissent avec l'application.",
    freeSoftware:
      'Cette application est un logiciel libre, sous licence GNU General Public License version 3 ou ultérieure.',
    stockfish:
      "L'application inclut Stockfish, publié sous GPLv3. Comme Stockfish y est lié, toute l'application porte la même licence — et son code source complet est publié.",
    reckless:
      "Elle comprend également Reckless, un second moteur, sous licence AGPLv3. Les deux licences se combinent, et la clause Affero sur les logiciels utilisés à travers un réseau ne change rien ici : les deux moteurs tournent sur cet appareil et l'app ne fait aucune requête réseau.",
    coaching: "L'entraîneur évalue chacun de vos coups au fur et à mesure.",
    online:
      "Un vrai adversaire via Game Center, à la pendule. Pas d'indice, pas de moteur, pas de retour en arrière.",
    photo: 'Lire un échiquier depuis une photo',
    takeOver: 'Continuer à partir d’ici',
    freeForever:
      "Jouer reste gratuit — contre le moteur comme contre des personnes, sans limite et sans publicité. Ce que Pro débloque, c'est l'entraînement.",
    allowance:
      "Le quota repart chaque jour à 9 h, heure locale. Jouer — contre le moteur ou contre quelqu'un — reste illimité et gratuit.",
    noAds: "Aucune publicité, nulle part dans l'app, jamais",
    unlimitedPuzzles: 'Les 14 351 problèmes, autant par jour que vous voulez',
    unlimitedRush: 'Des runs Rush sans limite quotidienne',
    unlimitedRest: "Jugement positionnel, finales et Devinez l'Elo, sans limite",
    renewal:
      "L'abonnement mensuel se renouvelle chaque mois jusqu'à résiliation. Vous pouvez résilier à tout moment dans Réglages › Compte Apple › Abonnements, au moins un jour avant le renouvellement. L'achat unique est un paiement unique et ne se renouvelle jamais.",
    pro: 'Brass Pawn Pro',
    monthly: 'Mensuel',
    lifetime: 'Achat unique',
    privacyPolicy: 'Politique de confidentialité',
    termsOfUse: "Conditions d'utilisation",
    licence: 'Licence',
    credits: 'Remerciements',
  },
  modes: {
    play: 'Jouer',
    watch: 'Regarder',
    tactics: 'Tactique',
    positional: 'Positionnel',
    endgames: 'Finales',
    guess: "Devinez l'Elo",
    online: 'En ligne',
    progress: 'Progression',
    rush: 'Rush',
  },
  shots: {
    title: ['Chaque coup que vous jouez,', 'commenté.'],
    mistake: ['Il ne dit pas seulement', 'que vous avez perdu.'],
    values: ['Ce que vaut chaque coup.', 'Avant de le jouer.'],
    library: ['Neuf cents parties', 'qui valent le détour.'],
    engines: ['Deux moteurs.', 'Un deuxième avis.'],
    coached: ['Et quand vous voyez juste,', 'il le dit.'],
    free: ['Cinq de chaque,', 'gratuitement.'],
  },
  spoken: {
    watch:
      'Neuf cents parties qui valent le détour. Trouvez-en une, suivez-la — et dès que vous auriez joué autrement, prenez la main.',
    tactics:
      'Quatorze mille exercices, choisis selon ce que vous ratez. Puis vous voyez ce que vaut chaque coup — avant de le jouer.',
    play: 'Le moyen le plus rapide de progresser aux échecs ? Savoir pourquoi chaque coup a marché. Brass Pawn vous le dit — coup après coup.',
  },
  ui: {
    category: "un entraîneur d'échecs pour iPhone et iPad",
    support: 'Assistance',
    language: 'Langue',
    menu: 'Menu',
    close: 'Fermer',
    skip: 'Aller au contenu',
    inEnglish: 'en anglais',
    film: "Voyez-la à l'œuvre",
    screens: 'Chaque écran',
    price: 'Ce que ça coûte',
    questions: 'Questions',
    narrated: 'Avec commentaire',
    silent: 'Sans le son',
    play: 'Lire',
    pause: 'Pause',
    download: "Télécharger dans l'App Store",
    soon: "Bientôt sur l'App Store",
    more: "En savoir plus sur l'app",
    free: 'Gratuit chaque jour',
    faq: [
      'Faut-il une connexion internet ?',
      "Qu'est-ce qui est gratuit ?",
      "Comment fonctionne l'abonnement ?",
      'Puis-je voir le code source ?',
    ],
    prices:
      "Les prix affichés sont ceux de l'App Store américain. Votre prix local est fixé par l'App Store.",
  },
};
