// Hebrew (he). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'שחק · התאמן · צפה',
    lede: 'טקטיקה, שיפוט עמדתי, טכניקת סופים ומשחקים עם אימון — כאשר המנוע רץ על המכשיר עצמו. שום דבר לא יוצא מהטלפון.',
    privacy:
      'האפליקציה לא אוספת דבר, לא שולחת דבר ולא מבצעת פניות רשת. הדירוגים וההיסטוריה שלך נשמרים רק במכשיר הזה, ונמחקים יחד עם האפליקציה.',
    freeSoftware:
      'אפליקציה זו היא תוכנה חופשית, ברישיון GNU General Public License גרסה 3 או מאוחרת יותר.',
    stockfish:
      'האפליקציה כוללת את Stockfish, המופץ ברישיון GPLv3. מכיוון ש-Stockfish מקושר לאפליקציה, כל האפליקציה כפופה לאותו רישיון — וקוד המקור המלא שלה פורסם.',
    reckless:
      'האפליקציה כוללת גם את Reckless, מנוע שני, ברישיון AGPLv3. שני הרישיונות משתלבים, וסעיף Affero בנוגע לתוכנה שנעשה בה שימוש דרך רשת אינו משנה כאן דבר: שני המנועים פועלים על המכשיר הזה, והאפליקציה אינה מבצעת שום פנייה לרשת.',
    coaching: 'המאמן מדרג כל מהלך שלך ברגע שאתה עושה אותו.',
    online: 'יריב אמיתי דרך Game Center, עם שעון. בלי רמזים, בלי מנוע, בלי לקחת מהלכים בחזרה.',
    photo: 'קריאת לוח מתמונה',
    takeOver: 'המשך לשחק מכאן',
    freeForever:
      'המשחק נשאר חינם — מול המנוע ומול אנשים, בלי הגבלה ובלי פרסומות. מה ש-Pro פותח זה האימון.',
    allowance:
      'המכסה מתאפסת בכל יום ב-9:00 לפי השעון המקומי. משחק — מול המנוע או מול אדם — הוא ללא הגבלה ובחינם.',
    noAds: 'בלי פרסומות, בשום מקום באפליקציה, אף פעם',
    unlimitedPuzzles: 'כל 14,351 התרגילים, כמה שתרצה ביום',
    unlimitedRush: 'סבבים ללא מגבלה יומית',
    unlimitedRest: 'שיפוט עמדתי, תרגילי סופים וניחוש הדירוג — ללא הגבלה',
    renewal:
      'התוכנית החודשית מתחדשת מדי חודש עד שתבטל. אפשר לבטל בכל עת בהגדרות › חשבון Apple › מינויים, לפחות יום לפני החידוש. הרכישה החד-פעמית היא תשלום יחיד ולעולם אינה מתחדשת.',
    pro: 'Brass Pawn Pro',
    monthly: 'חודשי',
    lifetime: 'רכישה חד-פעמית',
    privacyPolicy: 'מדיניות פרטיות',
    termsOfUse: 'תנאי שימוש',
    licence: 'רישיון',
    credits: 'קרדיטים',
  },
  modes: {
    play: 'שחק',
    watch: 'צפייה',
    tactics: 'טקטיקה',
    positional: 'עמדתי',
    endgames: 'סופים',
    guess: 'נחש את הדירוג',
    online: 'מקוון',
    progress: 'התקדמות',
    rush: 'ראש',
  },
  shots: {
    title: ['כל מהלך שאתה משחק,', 'מוסבר לך.'],
    mistake: ['הוא לא רק אומר', 'שהפסדת.'],
    values: ['כמה שווה כל מהלך.', 'לפני שאתה משחק.'],
    library: ['תשע מאות משחקים', 'ששווה לראות.'],
    engines: ['שני מנועים.', 'דעה שנייה.'],
    coached: ['וכשאתה קולע,', 'הוא אומר.'],
    free: ['חמישה מכל דבר,', 'בחינם.'],
  },
  spoken: {
    watch: 'תשע מאות משחקים ששווה לראות. מצא אחד, עקוב אחריו — וברגע שהיית משחק אחרת, קח פיקוד.',
    tactics:
      'ארבעה עשר אלף תרגילים, נבחרים ממה שאתה טועה בו. ואז רואים כמה שווה כל מהלך — לפני שמשחקים אותו.',
    play: 'הדרך המהירה ביותר להשתפר בשחמט? לדעת למה כל מהלך עבד. Brass Pawn אומר לך — מהלך אחר מהלך.',
  },
  ui: {
    category: 'מאמן שחמט ל‑iPhone ול‑iPad',
    support: 'תמיכה',
    language: 'שפה',
    menu: 'תפריט',
    close: 'סגירה',
    film: 'ראה אותה בפעולה',
    screens: 'כל מסך',
    price: 'כמה זה עולה',
    questions: 'שאלות',
    narrated: 'עם קריינות',
    silent: 'בלי קול',
    play: 'נגן',
    pause: 'השהיה',
    download: 'הורדה מ‑App Store',
    soon: 'בקרוב ב‑App Store',
    more: 'עוד על האפליקציה',
    free: 'בחינם כל יום',
    faq: ['צריך חיבור לאינטרנט?', 'מה חינם?', 'איך עובד המנוי?', 'אפשר לראות את קוד המקור?'],
    prices: 'המחירים המוצגים הם של App Store בארצות הברית. המחיר המקומי שלך נקבע על ידי App Store.',
  },
};
