// Hindi (hi). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'खेलें · अभ्यास · देखें',
    lede: 'रणनीति, स्थिति का आकलन, अंत-खेल तकनीक और कोचिंग के साथ बाज़ियाँ — इंजन डिवाइस पर ही चलता है। कुछ भी फ़ोन से बाहर नहीं जाता।',
    privacy:
      'ऐप कुछ भी इकट्ठा नहीं करता, कुछ भी नहीं भेजता और कोई नेटवर्क अनुरोध नहीं करता। आपकी रेटिंग और इतिहास सिर्फ़ इसी डिवाइस पर रहते हैं और ऐप हटाने पर मिट जाते हैं।',
    freeSoftware:
      'यह ऐप मुक्त सॉफ़्टवेयर है, GNU Affero General Public License संस्करण 3 या उसके बाद के तहत।',
    stockfish:
      'इस ऐप में Stockfish शामिल है, जो GPLv3 के तहत जारी होता है। चूँकि Stockfish ऐप से जुड़ा है, पूरा ऐप उसी लाइसेंस के अधीन है — और इसका पूरा स्रोत कोड प्रकाशित है।',
    reckless:
      'इसमें Reckless भी शामिल है, एक दूसरा इंजन, जो AGPLv3 के अंतर्गत है। दोनों लाइसेंस साथ चल सकते हैं, और नेटवर्क पर इस्तेमाल होने वाले सॉफ़्टवेयर से जुड़ा Affero खंड यहाँ कुछ नहीं बदलता: दोनों इंजन इसी डिवाइस पर चलते हैं और ऐप कोई नेटवर्क अनुरोध नहीं करता।',
    coaching: 'कोच आपकी हर चाल का मूल्यांकन उसी समय करता है।',
    online:
      'Game Center के ज़रिए असली प्रतिद्वंद्वी, घड़ी के साथ। कोई संकेत नहीं, कोई इंजन नहीं, चाल वापस लेना नहीं।',
    photo: 'फ़ोटो से बोर्ड पढ़ें',
    takeOver: 'यहाँ से खेलना जारी रखें',
    freeForever:
      'खेलना मुफ़्त ही रहेगा — इंजन के साथ भी और लोगों के साथ भी, बिना सीमा और बिना विज्ञापन। Pro जो खोलता है वह अभ्यास है।',
    allowance:
      'सीमा हर दिन स्थानीय समयानुसार सुबह 9 बजे फिर से शुरू होती है। खेलना — इंजन के साथ या किसी व्यक्ति के साथ — बिना सीमा और मुफ़्त है।',
    noAds: 'ऐप के किसी भी हिस्से में, कभी भी कोई विज्ञापन नहीं',
    unlimitedPuzzles: 'पूरी 14,351 पहेलियाँ, रोज़ जितनी चाहें',
    unlimitedRush: 'रोज़ की सीमा के बिना रश दौर',
    unlimitedRest: 'स्थिति का आकलन, अंत-खेल अभ्यास और रेटिंग पहचानना — बिना सीमा',
    renewal:
      'मासिक योजना हर महीने तब तक नवीनीकृत होती है जब तक आप रद्द न करें। सेटिंग्स › Apple खाता › सदस्यताएँ में कभी भी, नवीनीकरण से कम से कम एक दिन पहले रद्द किया जा सकता है। एक बार का भुगतान सिर्फ़ एक ही भुगतान है और कभी नवीनीकृत नहीं होता।',
    pro: 'Brass Pawn Pro',
    monthly: 'मासिक',
    lifetime: 'एक बार का भुगतान',
    privacyPolicy: 'निजता नीति',
    termsOfUse: 'उपयोग की शर्तें',
    licence: 'लाइसेंस',
    credits: 'श्रेय',
  },
  modes: {
    play: 'खेलें',
    watch: 'देखें',
    tactics: 'रणनीति',
    positional: 'स्थितिगत',
    endgames: 'अंत-खेल',
    guess: 'रेटिंग पहचानिए',
    online: 'ऑनलाइन',
    progress: 'प्रगति',
    rush: 'रश',
  },
  shots: {
    title: ['आपकी हर चाल,', 'समझाकर।'],
    mistake: ['यह सिर्फ़ यह नहीं बताता', 'कि आप हारे।'],
    values: ['हर चाल की कीमत।', 'चलने से पहले।'],
    library: ['देखने लायक', 'नौ सौ बाज़ियाँ।'],
    engines: ['दो इंजन।', 'दूसरी राय।'],
    coached: ['और जब सही चलें,', 'यह कहता है।'],
    free: ['हर चीज़ के पाँच,', 'मुफ़्त।'],
  },
  spoken: {
    watch:
      'देखने लायक नौ सौ बाज़ियाँ। एक चुनिए, देखिए — और जहाँ आप अलग चाल चलते, वहीं से खुद खेलिए।',
    tactics:
      'चौदह हज़ार पहेलियाँ, आपकी गलतियों से चुनी हुई। और फिर देखिए हर चाल की कीमत — चलने से पहले।',
    play: 'शतरंज में सबसे तेज़ी से बेहतर होने का तरीका? जानिए हर चाल क्यों काम आई। Brass Pawn बताता है — हर चाल पर।',
  },
  ui: {
    category: 'iPhone और iPad के लिए एक शतरंज प्रशिक्षक',
    support: 'सहायता',
    language: 'भाषा',
    menu: 'मेन्यू',
    close: 'बंद करें',
    film: 'इसे चलते हुए देखिए',
    screens: 'हर स्क्रीन',
    price: 'कीमत क्या है',
    questions: 'सवाल',
    narrated: 'कमेंट्री के साथ',
    silent: 'बिना आवाज़',
    play: 'चलाएँ',
    pause: 'रोकें',
    download: 'App Store से डाउनलोड करें',
    soon: 'जल्द ही App Store पर',
    more: 'ऐप के बारे में और',
    free: 'हर दिन मुफ़्त',
    faq: [
      'क्या इसे इंटरनेट कनेक्शन चाहिए?',
      'मुफ़्त में क्या मिलता है?',
      'सदस्यता कैसे काम करती है?',
      'क्या मैं सोर्स कोड देख सकता हूँ?',
    ],
    prices: 'दिखाई गई कीमतें अमेरिकी App Store की हैं। आपकी स्थानीय कीमत App Store तय करता है।',
  },
};
