// Hungarian (hu). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Játék · Edzés · Nézés',
    lede: 'Taktika, állásértékelés, végjátéktechnika és edzővel kísért játszmák, a a motor pedig magán a készüléken fut. Semmi nem hagyja el a telefont.',
    privacy:
      'Az alkalmazás semmit nem gyűjt, semmit nem küld, és nem indít hálózati kérést. Az értékszámaid és az előzményeid csak ezen a készüléken vannak, és a törléssel együtt tűnnek el.',
    freeSoftware:
      'Ez az alkalmazás szabad szoftver, a GNU General Public License 3-as vagy későbbi verziója alatt.',
    stockfish:
      'Az alkalmazás tartalmazza a Stockfisht, amely GPLv3 alatt jelenik meg. Mivel a Stockfish be van linkelve, az egész alkalmazásra ugyanaz a licenc vonatkozik — és a teljes forráskódja nyilvános.',
    reckless:
      'Tartalmazza a Reckless nevű második motort is, amely AGPLv3 licencű. A két licenc összekapcsolható, és az Affero hálózaton keresztül használt szoftverről szóló kikötése itt semmit sem változtat: mindkét motor ezen az eszközön fut, és az alkalmazás nem küld hálózati kérést.',
    coaching: 'Az edző minden lépésedet értékeli, ahogy megteszed.',
    online:
      'Valódi ellenfél a Game Centeren keresztül, órával. Nincs tipp, nincs motor, nincs visszalépés.',
    photo: 'Tábla beolvasása fotóról',
    takeOver: 'Játék folytatása innen',
    freeForever:
      'A játék ingyenes marad — a motor és emberek ellen is, korlát és reklám nélkül. A Pro az edzést oldja fel.',
    allowance:
      'A keret minden nap 9:00-kor, helyi idő szerint nullázódik. A játék — a motor vagy egy ember ellen — korlátlan és ingyenes.',
    noAds: 'Semmilyen reklám, az alkalmazás semelyik részén, soha',
    unlimitedPuzzles: 'Mind a 14 351 feladvány, naponta annyi, amennyit akarsz',
    unlimitedRush: 'Rush-körök napi korlát nélkül',
    unlimitedRest: 'Állásértékelés, végjáték-gyakorlatok és Élő-találgatás korlátlanul',
    renewal:
      'A havi csomag minden hónapban megújul, amíg le nem mondod. Bármikor lemondhatod a Beállítások › Apple-fiók › Előfizetések menüben, legkésőbb egy nappal a megújulás előtt. Az egyszeri feloldás egyetlen fizetés, és soha nem újul meg.',
    pro: 'Brass Pawn Pro',
    monthly: 'Havi',
    lifetime: 'Egyszeri feloldás',
    privacyPolicy: 'Adatvédelmi tájékoztató',
    termsOfUse: 'Felhasználási feltételek',
    licence: 'Licenc',
    credits: 'Közreműködők',
  },
  modes: {
    play: 'Játék',
    watch: 'Nézés',
    tactics: 'Taktika',
    positional: 'Pozíciós',
    endgames: 'Végjátékok',
    guess: 'Találd ki az Élőt',
    online: 'Online',
    progress: 'Fejlődés',
    rush: 'Rush',
  },
  shots: {
    title: ['Minden lépésed,', 'visszaolvasva.'],
    mistake: ['Nem csak annyit mond,', 'hogy vesztettél.'],
    values: ['Mit ér minden lépés.', 'Mielőtt lépnél.'],
    library: ['Kilencszáz parti,', 'amit érdemes végignézni.'],
    engines: ['Két motor.', 'Egy második vélemény.'],
    coached: ['És ha eltaláltad,', 'meg is mondja.'],
    free: ['Mindenből öt,', 'ingyen.'],
  },
  spoken: {
    watch:
      'Kilencszáz parti, amit érdemes végignézni. Válassz egyet — és amint másképp léptél volna, vedd át te.',
    tactics:
      'Tizennégyezer feladvány, abból válogatva, ami nem megy. Aztán látod, mit ér minden lépés — mielőtt lépnél.',
    play: 'A leggyorsabb út a jobb sakkhoz? Tudni, miért működött minden lépés. A Brass Pawn megmondja — lépésről lépésre.',
  },
  ui: {
    category: 'sakkedző iPhone-ra és iPadre',
    support: 'Támogatás',
    language: 'Nyelv',
    menu: 'Menü',
    close: 'Bezárás',
    film: 'Nézd meg működés közben',
    screens: 'Minden képernyő',
    price: 'Mennyibe kerül',
    questions: 'Kérdések',
    narrated: 'Narrációval',
    silent: 'Hang nélkül',
    play: 'Lejátszás',
    pause: 'Szünet',
    download: 'Letöltés az App Store-ból',
    soon: 'Hamarosan az App Store-ban',
    more: 'Többet az appról',
    free: 'Minden nap ingyen',
    faq: [
      'Kell hozzá internetkapcsolat?',
      'Mi az, ami ingyenes?',
      'Hogyan működik az előfizetés?',
      'Megnézhetem a forráskódot?',
    ],
    prices:
      'A feltüntetett árak az amerikai App Store árai. A helyi árat az App Store állapítja meg.',
  },
};
