// Indonesian (id). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Main · Latih · Tonton',
    lede: 'Taktik, penilaian posisi, teknik akhir permainan, dan partai berpendamping, dengan mesin berjalan di perangkat itu sendiri. Tidak ada yang meninggalkan ponsel.',
    privacy:
      'Aplikasi tidak mengumpulkan apa pun, tidak mengirim apa pun, dan tidak melakukan permintaan jaringan. Rating dan riwayatmu hanya tersimpan di perangkat ini dan ikut terhapus bersama aplikasi.',
    freeSoftware:
      'Aplikasi ini adalah perangkat lunak bebas, dilisensikan di bawah GNU General Public License versi 3 atau yang lebih baru.',
    stockfish:
      'Aplikasi ini menyertakan Stockfish yang dirilis dengan lisensi GPLv3. Karena Stockfish ditautkan ke dalam aplikasi, seluruh aplikasi memakai lisensi yang sama — dan kode sumbernya diterbitkan lengkap.',
    reckless:
      'Aplikasi ini juga menyertakan Reckless, mesin kedua, yang berlisensi AGPLv3. Kedua lisensi dapat digabungkan, dan klausul Affero tentang perangkat lunak yang digunakan melalui jaringan tidak mengubah apa pun di sini: kedua mesin berjalan di perangkat ini dan aplikasi tidak membuat permintaan jaringan.',
    coaching: 'Pelatih menilai setiap langkah Anda begitu Anda memainkannya.',
    online:
      'Lawan sungguhan lewat Game Center, dengan jam. Tanpa petunjuk, tanpa mesin, tanpa menarik langkah kembali.',
    photo: 'Baca papan dari foto',
    takeOver: 'Lanjutkan bermain dari sini',
    freeForever:
      'Bermain tetap gratis — lawan mesin maupun lawan orang, tanpa batas dan tanpa iklan. Yang dibuka Pro adalah latihannya.',
    allowance:
      'Jatahnya direset setiap hari pukul 09.00 waktu setempat. Bermain — lawan mesin atau lawan orang — tanpa batas dan gratis.',
    noAds: 'Tanpa iklan, di bagian mana pun, selamanya',
    unlimitedPuzzles: 'Semua 14.351 soal, sebanyak yang kamu mau tiap hari',
    unlimitedRush: 'Sesi Rush tanpa batas harian',
    unlimitedRest: 'Penilaian posisi, latihan akhir permainan, dan Tebak Elo tanpa batas',
    renewal:
      'Paket bulanan diperpanjang tiap bulan sampai kamu batalkan. Batalkan kapan saja di Pengaturan › Akun Apple › Langganan, paling lambat sehari sebelum perpanjangan. Pembukaan sekali bayar adalah pembayaran tunggal dan tidak pernah diperpanjang.',
    pro: 'Brass Pawn Pro',
    monthly: 'Bulanan',
    lifetime: 'Sekali bayar',
    privacyPolicy: 'Kebijakan Privasi',
    termsOfUse: 'Ketentuan Penggunaan',
    licence: 'Lisensi',
    credits: 'Kredit',
  },
  modes: {
    play: 'Main',
    watch: 'Tonton',
    tactics: 'Taktik',
    positional: 'Posisional',
    endgames: 'Akhir permainan',
    guess: 'Tebak Elo',
    online: 'Daring',
    progress: 'Kemajuan',
    rush: 'Rush',
  },
  shots: {
    title: ['Setiap langkah Anda,', 'dibacakan kembali.'],
    mistake: ['Bukan cuma memberi tahu', 'bahwa Anda kalah.'],
    values: ['Nilai setiap langkah.', 'Sebelum Anda melangkah.'],
    library: ['Sembilan ratus partai', 'yang layak ditonton.'],
    engines: ['Dua mesin.', 'Pendapat kedua.'],
    coached: ['Dan saat Anda benar,', 'ia mengatakannya.'],
    free: ['Lima dari tiap jenis,', 'gratis.'],
  },
  spoken: {
    watch:
      'Sembilan ratus partai yang layak ditonton. Pilih satu, ikuti — dan begitu Anda akan melangkah berbeda, ambil alih.',
    tactics:
      'Empat belas ribu teka-teki, dipilih dari yang sering Anda salah. Lalu lihat nilai setiap langkah — sebelum melangkah.',
    play: 'Cara tercepat menjadi lebih baik dalam catur? Tahu mengapa setiap langkah berhasil. Brass Pawn memberi tahu Anda — langkah demi langkah.',
  },
  ui: {
    category: 'pelatih catur untuk iPhone dan iPad',
    support: 'Dukungan',
    language: 'Bahasa',
    menu: 'Menu',
    close: 'Tutup',
    skip: 'Lompat ke konten',
    inEnglish: 'dalam bahasa Inggris',
    film: 'Lihat cara kerjanya',
    screens: 'Setiap layar',
    price: 'Berapa harganya',
    questions: 'Pertanyaan',
    narrated: 'Dengan narasi',
    silent: 'Tanpa suara',
    play: 'Putar',
    pause: 'Jeda',
    download: 'Unduh di App Store',
    soon: 'Segera di App Store',
    more: 'Selengkapnya tentang aplikasi',
    free: 'Gratis setiap hari',
    faq: [
      'Apakah perlu koneksi internet?',
      'Apa saja yang gratis?',
      'Bagaimana cara kerja langganannya?',
      'Bisakah saya melihat kode sumbernya?',
    ],
    prices:
      'Harga yang ditampilkan adalah harga App Store AS. Harga lokal Anda ditetapkan oleh App Store.',
  },
};
