// Italian (it). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Gioca · Allenati · Guarda',
    lede: 'Tattica, giudizio posizionale, tecnica di finale e partite commentate, con il motore che gira sul dispositivo. Niente esce dal telefono.',
    privacy:
      "L'app non raccoglie nulla, non invia nulla e non fa richieste di rete. I tuoi punteggi e la tua cronologia restano solo su questo dispositivo e si cancellano con l'app.",
    freeSoftware:
      'Questa applicazione è software libero, con licenza GNU General Public License versione 3 o successiva.',
    stockfish:
      "Include Stockfish, distribuito con licenza GPLv3. Poiché Stockfish è collegato all'app, l'intera applicazione porta la stessa licenza — e il suo codice sorgente completo è pubblicato.",
    reckless:
      "Include anche Reckless, un secondo motore, con licenza AGPLv3. Le due licenze si combinano, e la clausola Affero sul software usato attraverso una rete qui non cambia nulla: entrambi i motori girano su questo dispositivo e l'app non effettua richieste di rete.",
    coaching: "L'allenatore valuta ogni tua mossa nel momento in cui la giochi.",
    online:
      "Un avversario vero tramite Game Center, con l'orologio. Nessun suggerimento, nessun motore, nessuna mossa ritirata.",
    photo: 'Leggi una scacchiera da una foto',
    takeOver: 'Continua a giocare da qui',
    freeForever:
      "Giocare resta gratis — contro il motore e contro le persone, senza limiti e senza pubblicità. Quello che Pro sblocca è l'allenamento.",
    allowance:
      'Il conteggio riparte ogni giorno alle 9:00, ora locale. Giocare — contro il motore o contro una persona — è senza limiti e non costa nulla.',
    noAds: "Nessuna pubblicità, in nessuna parte dell'app, mai",
    unlimitedPuzzles: 'Tutti i 14.351 esercizi, quanti ne vuoi al giorno',
    unlimitedRush: 'Serie Rush senza limite giornaliero',
    unlimitedRest: "Giudizio posizionale, finali e Indovina l'Elo, senza limiti",
    renewal:
      'Il piano mensile si rinnova ogni mese finché non lo disdici. Puoi disdire quando vuoi in Impostazioni › Account Apple › Abbonamenti, almeno un giorno prima del rinnovo. Lo sblocco una tantum è un pagamento singolo e non si rinnova mai.',
    pro: 'Brass Pawn Pro',
    monthly: 'Mensile',
    lifetime: 'Sblocco una tantum',
    privacyPolicy: 'Informativa sulla privacy',
    termsOfUse: "Termini d'uso",
    licence: 'Licenza',
    credits: 'Riconoscimenti',
  },
  modes: {
    play: 'Gioca',
    watch: 'Guarda',
    tactics: 'Tattica',
    positional: 'Posizionale',
    endgames: 'Finali',
    guess: "Indovina l'Elo",
    online: 'Online',
    progress: 'Progressi',
    rush: 'Rush',
  },
  shots: {
    title: ['Ogni mossa che giochi,', 'spiegata.'],
    mistake: ['Non ti dice soltanto', 'che hai perso.'],
    values: ['Quanto vale ogni mossa.', 'Prima di giocarla.'],
    library: ['Novecento partite', 'che vale la pena guardare.'],
    engines: ['Due motori.', 'Un secondo parere.'],
    coached: ['E quando ci prendi,', 'te lo dice.'],
    free: ['Cinque di tutto,', 'gratis.'],
  },
  spoken: {
    watch:
      'Novecento partite che vale la pena guardare. Scegline una, seguila — e appena avresti giocato diversamente, prendila in mano.',
    tactics:
      'Quattordicimila esercizi, scelti da ciò che sbagli. E poi vedi quanto vale ogni mossa — prima di giocarla.',
    play: 'Il modo più rapido per migliorare a scacchi? Sapere perché ogni mossa ha funzionato. Brass Pawn te lo dice — mossa dopo mossa.',
  },
  ui: {
    category: 'un allenatore di scacchi per iPhone e iPad',
    support: 'Assistenza',
    language: 'Lingua',
    menu: 'Menu',
    close: 'Chiudi',
    skip: 'Vai al contenuto',
    inEnglish: 'in inglese',
    film: "Guardala all'opera",
    screens: 'Ogni schermata',
    price: 'Quanto costa',
    questions: 'Domande',
    narrated: 'Con la voce narrante',
    silent: 'Senza audio',
    play: 'Riproduci',
    pause: 'Pausa',
    download: 'Scaricala su App Store',
    soon: 'Presto su App Store',
    more: "Altro sull'app",
    free: 'Gratis ogni giorno',
    faq: [
      'Serve una connessione a internet?',
      'Che cosa è gratis?',
      "Come funziona l'abbonamento?",
      'Posso vedere il codice sorgente?',
    ],
    prices:
      "I prezzi mostrati sono quelli dell'App Store statunitense. Il tuo prezzo locale lo stabilisce l'App Store.",
  },
};
