// Japanese (ja). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: '指す · 鍛える · 観る',
    lede: '戦術、局面判断、終盤技術、そして解説つきの対局。エンジン は端末上で動作し、データが端末の外に出ることはありません。',
    privacy:
      '本アプリは何も収集せず、何も送信せず、ネットワーク通信も行いません。レーティングと履歴はこの端末にのみ保存され、アプリを削除すれば一緒に消えます。',
    freeSoftware:
      '本アプリはフリーソフトウェアであり、GNU General Public License バージョン 3 以降の条件で配布されています。',
    stockfish:
      '本アプリには GPLv3 で公開されている Stockfish が含まれます。Stockfish をリンクしているため、アプリ全体が同じライセンスに従い、そのソースコードはすべて公開されています。',
    reckless:
      'AGPLv3 の第二のエンジン Reckless も含まれています。二つのライセンスは併存でき、ネットワーク越しに利用されるソフトウェアに関する Affero 条項はここでは何も変えません。どちらのエンジンもこの端末上で動作し、アプリはネットワーク通信を一切行いません。',
    coaching: 'コーチが、指したそばから一手ごとに評価します。',
    online:
      'Game Center を通じた生身の相手と、持ち時間つきで対局します。ヒントなし、エンジンなし、待ったなし。',
    photo: '写真から盤面を読む',
    takeOver: 'ここから指し継ぐ',
    freeForever:
      '対局は無料のままです — エンジン相手でも人相手でも、制限なし・広告なし。Pro が解放するのはトレーニングです。',
    allowance:
      '回数は毎日午前 9 時（現地時間）に戻ります。対局はエンジン相手でも人相手でも無制限、無料のままです。',
    noAds: 'アプリのどこにも、いつまでも広告なし',
    unlimitedPuzzles: '14,351 問すべて、1 日に何問でも',
    unlimitedRush: '1 日の回数制限なしのラッシュ',
    unlimitedRest: '局面判断・終盤ドリル・レーティング当てが無制限',
    renewal:
      '月額プランは解約するまで毎月自動更新されます。解約は「設定 › Apple アカウント › サブスクリプション」から、更新日の 1 日前までにいつでも行えます。買い切りは一度きりの支払いで、更新はありません。',
    pro: 'Brass Pawn Pro',
    monthly: '月額',
    lifetime: '買い切り',
    privacyPolicy: 'プライバシーポリシー',
    termsOfUse: '利用規約',
    licence: 'ライセンス',
    credits: '謝辞',
  },
  modes: {
    play: '対局',
    watch: '観る',
    tactics: '戦術',
    positional: '局面判断',
    endgames: '終盤',
    guess: 'レーティング当て',
    online: 'オンライン',
    progress: '上達',
    rush: 'ラッシュ',
  },
  shots: {
    title: ['あなたの一手を、', '読み解いて返す。'],
    mistake: ['負けたと告げるだけでは', '終わらない。'],
    values: ['一手ごとの価値を。', '指す前に。'],
    library: ['見る価値のある', '九百局。'],
    engines: ['エンジンは二つ。', 'second opinion。'],
    coached: ['正解したときは、', 'そう言ってくれる。'],
    free: ['どれも五回まで、', '無料。'],
  },
  spoken: {
    watch:
      '見る価値のある九百局。一局を選んで追いかけ、自分なら違う手を指す。その瞬間から、続きはあなたが。',
    tactics:
      '一万四千問。あなたが間違えたところから選ばれます。そして一手ごとの価値が、指す前に見えます。',
    play: 'チェスが最速で上達する方法は？ なぜその手が良かったのかを知ること。Brass Pawn が一手ごとに教えます。',
  },
  ui: {
    category: 'iPhone と iPad のためのチェス・トレーナー',
    support: 'サポート',
    language: '言語',
    menu: 'メニュー',
    close: '閉じる',
    skip: '本文へスキップ',
    inEnglish: '英語',
    film: '動くところを見る',
    screens: 'すべての画面',
    price: '料金',
    questions: 'よくある質問',
    narrated: 'ナレーションあり',
    silent: '音なし',
    play: '再生',
    pause: '一時停止',
    download: 'App Store からダウンロード',
    soon: 'App Store に近日登場',
    more: 'アプリについてもっと見る',
    free: '毎日無料で',
    faq: [
      'インターネット接続は必要ですか？',
      '無料で何ができますか？',
      'サブスクリプションの仕組みは？',
      'ソースコードは公開されていますか？',
    ],
    prices: '表示価格は米国 App Store のものです。お住まいの地域の価格は App Store が決定します。',
  },
};
