// Korean (ko). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: '대국 · 훈련 · 관전',
    lede: '전술, 포지션 판단, 엔드게임 기술, 그리고 코칭이 붙은 대국. 엔진이 기기 안에서 돌아가며, 어떤 데이터도 휴대폰을 떠나지 않습니다.',
    privacy:
      '이 앱은 아무것도 수집하지 않고, 아무것도 보내지 않으며, 네트워크 요청도 하지 않습니다. 레이팅과 기록은 이 기기에만 저장되고, 앱을 지우면 함께 사라집니다.',
    freeSoftware:
      '이 앱은 자유 소프트웨어이며, GNU General Public License 버전 3 이상으로 배포됩니다.',
    stockfish:
      '이 앱에는 GPLv3로 배포되는 Stockfish가 포함되어 있습니다. Stockfish가 앱에 링크되어 있으므로 앱 전체가 같은 라이선스를 따르며, 전체 소스 코드가 공개되어 있습니다.',
    reckless:
      'AGPLv3로 배포되는 두 번째 엔진 Reckless도 포함되어 있습니다. 두 라이선스는 함께 쓸 수 있으며, 네트워크를 통해 사용되는 소프트웨어에 관한 Affero 조항은 여기서 아무것도 바꾸지 않습니다. 두 엔진 모두 이 기기에서 실행되고, 앱은 어떤 네트워크 요청도 하지 않습니다.',
    coaching: '코치가 두는 즉시 매 수를 평가합니다.',
    online: 'Game Center로 만나는 진짜 상대, 시계까지. 힌트도, 엔진도, 무르기도 없습니다.',
    photo: '사진에서 보드 읽기',
    takeOver: '여기서 이어 두기',
    freeForever:
      '대국은 계속 무료입니다 — 엔진이든 사람이든, 제한도 광고도 없습니다. Pro가 여는 것은 훈련입니다.',
    allowance:
      '횟수는 매일 현지 시간 오전 9시에 초기화됩니다. 대국은 엔진이든 사람이든 제한 없이 무료입니다.',
    noAds: '앱 어디에도, 언제까지나 광고 없음',
    unlimitedPuzzles: '14,351문제 전부, 하루에 원하는 만큼',
    unlimitedRush: '하루 제한 없는 러시',
    unlimitedRest: '포지션 판단, 엔드게임 드릴, 레이팅 맞히기 무제한',
    renewal:
      '월간 요금제는 해지할 때까지 매달 자동으로 갱신됩니다. 설정 › Apple 계정 › 구독에서 갱신 하루 전까지 언제든 해지할 수 있습니다. 한 번만 결제하는 잠금 해제는 단일 결제이며 갱신되지 않습니다.',
    pro: 'Brass Pawn Pro',
    monthly: '월간',
    lifetime: '한 번만 결제',
    privacyPolicy: '개인정보 처리방침',
    termsOfUse: '이용약관',
    licence: '라이선스',
    credits: '만든 사람들',
  },
  modes: {
    play: '대국',
    watch: '관전',
    tactics: '전술',
    positional: '포지션',
    endgames: '엔드게임',
    guess: '레이팅 맞히기',
    online: '온라인',
    progress: '진행',
    rush: '러시',
  },
  shots: {
    title: ['당신이 둔 모든 수를,', '다시 읽어 줍니다.'],
    mistake: ['졌다고만', '말하지 않습니다.'],
    values: ['모든 수의 가치를.', '두기 전에.'],
    library: ['볼 만한', '구백 판의 명국.'],
    engines: ['엔진 둘.', '두 번째 의견.'],
    coached: ['잘 두었을 때도,', '그렇게 말합니다.'],
    free: ['종류마다 다섯 번,', '무료.'],
  },
  spoken: {
    watch:
      '볼 만한 구백 판의 명국. 하나를 골라 따라가다가, 다르게 두고 싶은 순간부터는 직접 이어서.',
    tactics:
      '만 사천 문제, 당신이 자주 틀리는 곳에서 고른 것들. 그리고 모든 수의 가치를 두기 전에 봅니다.',
    play: '체스 실력을 가장 빨리 올리는 방법? 왜 그 수가 좋았는지 아는 것. Brass Pawn이 한 수마다 알려줍니다.',
  },
  ui: {
    category: 'iPhone과 iPad를 위한 체스 트레이너',
    support: '지원',
    language: '언어',
    menu: '메뉴',
    close: '닫기',
    film: '움직이는 모습 보기',
    screens: '모든 화면',
    price: '가격',
    questions: '자주 묻는 질문',
    narrated: '해설 포함',
    silent: '소리 없이',
    play: '재생',
    pause: '일시정지',
    download: 'App Store에서 다운로드',
    soon: 'App Store에 곧 출시',
    more: '앱에 대해 더 보기',
    free: '매일 무료로',
    faq: [
      '인터넷 연결이 필요한가요?',
      '무료로 무엇을 할 수 있나요?',
      '구독은 어떻게 작동하나요?',
      '소스 코드를 볼 수 있나요?',
    ],
    prices: '표시된 가격은 미국 App Store 기준입니다. 현지 가격은 App Store가 정합니다.',
  },
};
