// Malay (ms). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Main · Latih · Tonton',
    lede: 'Taktik, penilaian kedudukan, teknik permainan akhir dan perlawanan berjurulatih, dengan enjin berjalan pada peranti itu sendiri. Tiada apa-apa meninggalkan telefon.',
    privacy:
      'Aplikasi tidak mengumpul apa-apa, tidak menghantar apa-apa dan tidak membuat permintaan rangkaian. Rating dan sejarah anda hanya tersimpan pada peranti ini dan terpadam bersama aplikasi.',
    freeSoftware:
      'Aplikasi ini ialah perisian bebas, dilesenkan di bawah GNU General Public License versi 3 atau lebih baharu.',
    stockfish:
      'Aplikasi ini menyertakan Stockfish yang dikeluarkan di bawah GPLv3. Oleh sebab Stockfish dipautkan ke dalam aplikasi, seluruh aplikasi memakai lesen yang sama — dan kod sumbernya diterbitkan sepenuhnya.',
    reckless:
      'Aplikasi ini turut menyertakan Reckless, enjin kedua, di bawah AGPLv3. Kedua-dua lesen boleh digabungkan, dan klausa Affero tentang perisian yang digunakan melalui rangkaian tidak mengubah apa-apa di sini: kedua-dua enjin berjalan pada peranti ini dan aplikasi tidak membuat sebarang permintaan rangkaian.',
    coaching: 'Jurulatih menilai setiap langkah anda sebaik sahaja anda memainkannya.',
    online:
      'Lawan sebenar melalui Game Center, dengan jam. Tiada petunjuk, tiada enjin, tiada tarik balik langkah.',
    photo: 'Baca papan daripada foto',
    takeOver: 'Teruskan bermain dari sini',
    freeForever:
      'Bermain kekal percuma — menentang enjin mahupun orang, tanpa had dan tanpa iklan. Yang dibuka oleh Pro ialah latihan.',
    allowance:
      'Kuota ditetapkan semula setiap hari pada pukul 9:00 pagi waktu tempatan. Bermain — menentang enjin atau menentang orang — tanpa had dan percuma.',
    noAds: 'Tiada iklan, di mana-mana bahagian aplikasi, selamanya',
    unlimitedPuzzles: 'Kesemua 14,351 teka-teki, seberapa banyak sehari yang anda mahu',
    unlimitedRush: 'Pusingan Rush tanpa had harian',
    unlimitedRest: 'Penilaian kedudukan, latihan permainan akhir dan Teka Elo tanpa had',
    renewal:
      'Pelan bulanan diperbaharui setiap bulan sehingga anda membatalkannya. Batalkan bila-bila masa di Tetapan › Akaun Apple › Langganan, sekurang-kurangnya sehari sebelum pembaharuan. Pembukaan sekali bayar ialah bayaran tunggal dan tidak pernah diperbaharui.',
    pro: 'Brass Pawn Pro',
    monthly: 'Bulanan',
    lifetime: 'Bayar sekali',
    privacyPolicy: 'Dasar Privasi',
    termsOfUse: 'Terma Penggunaan',
    licence: 'Lesen',
    credits: 'Penghargaan',
  },
  modes: {
    play: 'Main',
    watch: 'Tonton',
    tactics: 'Taktik',
    positional: 'Kedudukan',
    endgames: 'Permainan akhir',
    guess: 'Teka Elo',
    online: 'Dalam talian',
    progress: 'Kemajuan',
    rush: 'Rush',
  },
  shots: {
    title: ['Setiap langkah anda,', 'dibaca semula.'],
    mistake: ['Bukan sekadar memberitahu', 'yang anda kalah.'],
    values: ['Nilai setiap langkah.', 'Sebelum anda melangkah.'],
    library: ['Sembilan ratus perlawanan', 'yang berbaloi ditonton.'],
    engines: ['Dua enjin.', 'Pendapat kedua.'],
    coached: ['Dan apabila anda betul,', 'ia mengatakannya.'],
    free: ['Lima setiap satu,', 'percuma.'],
  },
  spoken: {
    watch:
      'Sembilan ratus perlawanan yang berbaloi ditonton. Pilih satu, ikuti — dan sebaik anda akan melangkah lain, ambil alih.',
    tactics:
      'Empat belas ribu teka-teki, dipilih daripada apa yang anda sering silap. Kemudian lihat nilai setiap langkah — sebelum melangkah.',
    play: 'Cara terpantas menjadi lebih baik dalam catur? Tahu mengapa setiap langkah berkesan. Brass Pawn beritahu anda — langkah demi langkah.',
  },
  ui: {
    category: 'jurulatih catur untuk iPhone dan iPad',
    support: 'Sokongan',
    language: 'Bahasa',
    menu: 'Menu',
    close: 'Tutup',
    film: 'Lihat cara ia berfungsi',
    screens: 'Setiap skrin',
    price: 'Berapa harganya',
    questions: 'Soalan',
    narrated: 'Dengan naratif',
    silent: 'Tanpa bunyi',
    play: 'Main',
    pause: 'Jeda',
    download: 'Muat turun di App Store',
    soon: 'Tidak lama lagi di App Store',
    more: 'Lagi tentang apl ini',
    free: 'Percuma setiap hari',
    faq: [
      'Adakah ia memerlukan sambungan internet?',
      'Apa yang percuma?',
      'Bagaimana langganan berfungsi?',
      'Bolehkah saya melihat kod sumbernya?',
    ],
    prices:
      'Harga yang dipaparkan ialah harga App Store AS. Harga tempatan anda ditetapkan oleh App Store.',
  },
};
