// Dutch (nl-NL). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Spelen · Trainen · Kijken',
    lede: 'Tactiek, positioneel inzicht, eindspeltechniek en partijen met begeleiding, met de engine op het toestel zelf. Er verlaat niets de telefoon.',
    privacy:
      'De app verzamelt niets, verstuurt niets en doet geen netwerkverzoeken. Je ratings en geschiedenis staan alleen op dit toestel en verdwijnen met de app.',
    freeSoftware:
      'Deze app is vrije software onder de GNU General Public License versie 3 of later.',
    stockfish:
      'De app bevat Stockfish, dat onder de GPLv3 valt. Omdat Stockfish erin gelinkt is, valt de hele app onder dezelfde licentie — en de volledige broncode is gepubliceerd.',
    reckless:
      'De app bevat ook Reckless, een tweede engine, onder de AGPLv3. De twee licenties gaan samen, en de Affero-bepaling over software die via een netwerk wordt gebruikt verandert hier niets: beide engines draaien op dit apparaat en de app doet geen netwerkverzoeken.',
    coaching: 'De coach beoordeelt elke zet zodra je hem doet.',
    online:
      'Een echte tegenstander via Game Center, met klok. Geen hints, geen engine, geen zetten terugnemen.',
    photo: 'Een bord van een foto lezen',
    takeOver: 'Vanaf hier verder spelen',
    freeForever:
      'Spelen blijft gratis — tegen de engine en tegen mensen, zonder limiet en zonder advertenties. Wat Pro ontgrendelt, is de training.',
    allowance:
      'Het tegoed gaat elke dag om 9:00 uur lokale tijd weer open. Spelen — tegen de engine of tegen iemand — is onbeperkt en gratis.',
    noAds: 'Geen advertenties, nergens in de app, nooit',
    unlimitedPuzzles: 'Alle 14.351 puzzels, zoveel per dag als je wilt',
    unlimitedRush: 'Rush-rondes zonder daglimiet',
    unlimitedRest: 'Positioneel inzicht, eindspeloefeningen en Raad de Elo, onbeperkt',
    renewal:
      'Het maandabonnement verlengt elke maand tot je opzegt. Opzeggen kan altijd via Instellingen › Apple-account › Abonnementen, uiterlijk een dag voor de verlenging. De eenmalige ontgrendeling is één betaling en verlengt nooit.',
    pro: 'Brass Pawn Pro',
    monthly: 'Maandelijks',
    lifetime: 'Eenmalig',
    privacyPolicy: 'Privacybeleid',
    termsOfUse: 'Gebruiksvoorwaarden',
    licence: 'Licentie',
    credits: 'Met dank aan',
  },
  modes: {
    play: 'Spelen',
    watch: 'Kijken',
    tactics: 'Tactiek',
    positional: 'Positioneel',
    endgames: 'Eindspelen',
    guess: 'Raad de Elo',
    online: 'Online',
    progress: 'Voortgang',
    rush: 'Rush',
  },
  shots: {
    title: ['Elke zet die je doet,', 'teruggelezen.'],
    mistake: ['Het zegt niet alleen', 'dat je verloor.'],
    values: ['Wat elke zet waard is.', 'Voordat je hem doet.'],
    library: ['Negenhonderd partijen', 'die het bekijken waard zijn.'],
    engines: ['Twee engines.', 'Een tweede mening.'],
    coached: ['En als je het goed ziet,', 'zegt het dat.'],
    free: ['Vijf van alles,', 'gratis.'],
  },
  spoken: {
    watch:
      'Negenhonderd partijen die het bekijken waard zijn. Kies er een, volg hem — en zodra jij anders had gezet, neem je het over.',
    tactics:
      'Veertienduizend puzzels, gekozen uit wat je blijft missen. En dan zie je wat elke zet waard is — voordat je hem doet.',
    play: 'De snelste manier om beter te schaken? Weten waarom elke zet werkte. Brass Pawn vertelt het je — zet voor zet.',
  },
  ui: {
    category: 'een schaaktrainer voor iPhone en iPad',
    support: 'Ondersteuning',
    language: 'Taal',
    menu: 'Menu',
    close: 'Sluiten',
    skip: 'Naar de inhoud',
    inEnglish: 'in het Engels',
    film: 'Zie het in actie',
    screens: 'Elk scherm',
    price: 'Wat het kost',
    questions: 'Vragen',
    narrated: 'Met commentaar',
    silent: 'Zonder geluid',
    play: 'Afspelen',
    pause: 'Pauze',
    download: 'Download in de App Store',
    soon: 'Binnenkort in de App Store',
    more: 'Meer over de app',
    free: 'Elke dag gratis',
    faq: [
      'Is er een internetverbinding nodig?',
      'Wat is gratis?',
      'Hoe werkt het abonnement?',
      'Kan ik de broncode inzien?',
    ],
    prices:
      'De getoonde prijzen zijn die van de Amerikaanse App Store. Je lokale prijs wordt door de App Store bepaald.',
  },
};
