// Norwegian (no). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Spill · Tren · Se',
    lede: 'Taktikk, posisjonsvurdering, sluttspillteknikk og partier med coaching, med motoren som kjører på selve enheten. Ingenting forlater telefonen.',
    privacy:
      'Appen samler ikke inn noe, sender ingenting og gjør ingen nettverkskall. Ratingene og historikken din ligger bare på denne enheten og slettes sammen med appen.',
    freeSoftware:
      'Denne appen er fri programvare, lisensiert under GNU General Public License versjon 3 eller nyere.',
    stockfish:
      'Appen inneholder Stockfish, som er utgitt under GPLv3. Fordi Stockfish er lenket inn i appen, omfattes hele appen av samme lisens — og hele kildekoden er offentliggjort.',
    reckless:
      'Appen inneholder også Reckless, en andre motor, under AGPLv3. De to lisensene kan kombineres, og Affero-klausulen om programvare som brukes over et nettverk endrer ingenting her: begge motorene kjører på denne enheten, og appen gjør ingen nettverkskall.',
    coaching: 'Treneren vurderer hvert av trekkene dine etter hvert som du gjør dem.',
    online:
      'En ekte motstander via Game Center, på klokke. Ingen hint, ingen motor, ingen angrede trekk.',
    photo: 'Les et brett fra et foto',
    takeOver: 'Spill videre herfra',
    freeForever:
      'Å spille forblir gratis — mot motoren og mot mennesker, uten grense og uten reklame. Det Pro låser opp, er treningen.',
    allowance:
      'Kvoten nullstilles hver dag kl. 09.00 lokal tid. Å spille — mot motoren eller mot et menneske — er uten grense og gratis.',
    noAds: 'Ingen reklame, ingen steder i appen, aldri',
    unlimitedPuzzles: 'Alle 14 351 oppgavene, så mange per dag du vil',
    unlimitedRush: 'Rush-runder uten daglig grense',
    unlimitedRest: 'Posisjonsvurdering, sluttspilløvelser og Gjett ratingen, uten grense',
    renewal:
      'Månedsplanen fornyes hver måned til du sier den opp. Du kan si opp når som helst i Innstillinger › Apple-konto › Abonnementer, senest en dag før fornyelsen. Engangskjøpet er én betaling og fornyes aldri.',
    pro: 'Brass Pawn Pro',
    monthly: 'Månedlig',
    lifetime: 'Engangskjøp',
    privacyPolicy: 'Personvernerklæring',
    termsOfUse: 'Bruksvilkår',
    licence: 'Lisens',
    credits: 'Medvirkende',
  },
  modes: {
    play: 'Spill',
    watch: 'Se',
    tactics: 'Taktikk',
    positional: 'Posisjon',
    endgames: 'Sluttspill',
    guess: 'Gjett ratingen',
    online: 'Online',
    progress: 'Utvikling',
    rush: 'Rush',
  },
  shots: {
    title: ['Hvert trekk du gjør,', 'lest tilbake.'],
    mistake: ['Den sier ikke bare', 'at du tapte.'],
    values: ['Hva hvert trekk er verdt.', 'Før du trekker.'],
    library: ['Ni hundre partier', 'verdt å se.'],
    engines: ['To motorer.', 'En annen mening.'],
    coached: ['Og når du treffer,', 'sier den det.'],
    free: ['Fem av hvert slag,', 'gratis.'],
  },
  spoken: {
    watch:
      'Ni hundre partier verdt å se. Finn ett, følg det — og i det øyeblikket du ville trukket annerledes, overta.',
    tactics:
      'Fjorten tusen oppgaver, valgt ut fra det du bommer på. Og så ser du hva hvert trekk er verdt — før du trekker.',
    play: 'Den raskeste veien til bedre sjakk? Å vite hvorfor hvert trekk fungerte. Brass Pawn forteller deg det — trekk for trekk.',
  },
  ui: {
    category: 'en sjakktrener for iPhone og iPad',
    support: 'Brukerstøtte',
    language: 'Språk',
    menu: 'Meny',
    close: 'Lukk',
    film: 'Se den i bruk',
    screens: 'Hver skjerm',
    price: 'Hva det koster',
    questions: 'Spørsmål',
    narrated: 'Med forteller',
    silent: 'Uten lyd',
    play: 'Spill av',
    pause: 'Pause',
    download: 'Last ned på App Store',
    soon: 'Snart på App Store',
    more: 'Mer om appen',
    free: 'Gratis hver dag',
    faq: [
      'Trenger den internettforbindelse?',
      'Hva er gratis?',
      'Hvordan fungerer abonnementet?',
      'Kan jeg se kildekoden?',
    ],
    prices:
      'Prisene som vises er fra den amerikanske App Store. Din lokale pris fastsettes av App Store.',
  },
};
