// Polish (pl). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Graj · Trenuj · Oglądaj',
    lede: 'Taktyka, ocena pozycji, technika końcówek i partie z komentarzem, ze silnikem działającym na urządzeniu. Nic nie opuszcza telefonu.',
    privacy:
      'Aplikacja niczego nie zbiera, niczego nie wysyła i nie łączy się z siecią. Twoje rankingi i historia są tylko na tym urządzeniu i znikają razem z aplikacją.',
    freeSoftware:
      'Ta aplikacja to wolne oprogramowanie na licencji GNU Affero General Public License w wersji 3 lub nowszej.',
    stockfish:
      'Aplikacja zawiera Stockfisha na licencji GPLv3. Ponieważ Stockfish jest z nią zlinkowany, cała aplikacja podlega tej samej licencji — a jej pełny kod źródłowy jest opublikowany.',
    reckless:
      'Zawiera także Reckless, drugi silnik, na licencji AGPLv3. Obie licencje dają się połączyć, a klauzula Affero dotycząca oprogramowania używanego przez sieć nic tu nie zmienia: oba silniki działają na tym urządzeniu, a aplikacja nie wysyła żadnych zapytań sieciowych.',
    coaching: 'Trener ocenia każdy Twój ruch zaraz po jego wykonaniu.',
    online:
      'Żywy przeciwnik przez Game Center, z zegarem. Bez podpowiedzi, bez silnika, bez cofania posunięć.',
    photo: 'Odczytaj szachownicę ze zdjęcia',
    takeOver: 'Graj dalej od tego miejsca',
    freeForever:
      'Gra pozostaje darmowa — z silnikiem i z ludźmi, bez limitu i bez reklam. Pro odblokowuje trening.',
    allowance:
      'Limit odnawia się codziennie o 9:00 czasu lokalnego. Gra — z silnikiem albo z człowiekiem — jest bez limitu i za darmo.',
    noAds: 'Żadnych reklam, w żadnej części aplikacji, nigdy',
    unlimitedPuzzles: 'Wszystkie 14 351 zadań, tyle dziennie, ile chcesz',
    unlimitedRush: 'Serie Rush bez dziennego limitu',
    unlimitedRest: 'Ocena pozycji, końcówki i Zgadnij Elo bez limitu',
    renewal:
      'Plan miesięczny odnawia się co miesiąc, dopóki go nie anulujesz. Anulować możesz w Ustawieniach › Konto Apple › Subskrypcje, najpóźniej dzień przed odnowieniem. Jednorazowe odblokowanie to pojedyncza płatność, która nigdy się nie odnawia.',
    pro: 'Brass Pawn Pro',
    monthly: 'Miesięcznie',
    lifetime: 'Jednorazowo',
    privacyPolicy: 'Polityka prywatności',
    termsOfUse: 'Warunki użytkowania',
    licence: 'Licencja',
    credits: 'Twórcy',
  },
  modes: {
    play: 'Graj',
    watch: 'Oglądaj',
    tactics: 'Taktyka',
    positional: 'Pozycyjne',
    endgames: 'Końcówki',
    guess: 'Zgadnij Elo',
    online: 'Online',
    progress: 'Postępy',
    rush: 'Rush',
  },
  shots: {
    title: ['Każdy twój ruch,', 'odczytany.'],
    mistake: ['Nie mówi tylko,', 'że przegrałeś.'],
    values: ['Ile wart jest każdy ruch.', 'Zanim go zagrasz.'],
    library: ['Dziewięćset partii', 'wartych obejrzenia.'],
    engines: ['Dwa silniki.', 'Druga opinia.'],
    coached: ['A gdy trafisz,', 'też to powie.'],
    free: ['Po pięć z każdego,', 'za darmo.'],
  },
  spoken: {
    watch:
      'Dziewięćset partii wartych obejrzenia. Znajdź jedną, śledź ją — a gdy zagrałbyś inaczej, przejmij ją.',
    tactics:
      'Czternaście tysięcy zadań, dobranych z tego, co ci nie wychodzi. A potem widzisz, ile wart jest każdy ruch — zanim go zagrasz.',
    play: 'Najszybszy sposób, by grać lepiej w szachy? Wiedzieć, dlaczego każdy ruch zadziałał. Brass Pawn ci powie — ruch po ruchu.',
  },
  ui: {
    category: "trener szachowy na iPhone'a i iPada",
    support: 'Pomoc',
    language: 'Język',
    menu: 'Menu',
    close: 'Zamknij',
    film: 'Zobacz, jak działa',
    screens: 'Każdy ekran',
    price: 'Ile to kosztuje',
    questions: 'Pytania',
    narrated: 'Z lektorem',
    silent: 'Bez dźwięku',
    play: 'Odtwórz',
    pause: 'Pauza',
    download: 'Pobierz w App Store',
    soon: 'Wkrótce w App Store',
    more: 'Więcej o aplikacji',
    free: 'Codziennie za darmo',
    faq: [
      'Czy potrzebuje połączenia z internetem?',
      'Co jest za darmo?',
      'Jak działa subskrypcja?',
      'Czy mogę zobaczyć kod źródłowy?',
    ],
    prices: 'Podane ceny pochodzą z amerykańskiego App Store. Twoją lokalną cenę ustala App Store.',
  },
};
