// Portuguese (Brazil) (pt-BR). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Jogar · Treinar · Assistir',
    lede: 'Tática, julgamento posicional, técnica de finais e partidas comentadas, com o o motor rodando no aparelho. Nada sai do telefone.',
    privacy:
      'O aplicativo não coleta nada, não envia nada e não faz requisições de rede. Seus ratings e seu histórico ficam só neste aparelho, e somem junto com o aplicativo.',
    freeSoftware:
      'Este aplicativo é software livre, licenciado sob a GNU General Public License versão 3 ou posterior.',
    stockfish:
      'Inclui o Stockfish, que é GPLv3. Como o Stockfish está ligado ao aplicativo, todo o aplicativo carrega a mesma licença — e o código-fonte completo está publicado.',
    reckless:
      'Também inclui o Reckless, um segundo motor, sob a AGPLv3. As duas licenças se combinam, e a cláusula Affero sobre software usado através de uma rede não muda nada aqui: os dois motores rodam neste aparelho e o app não faz nenhuma requisição de rede.',
    coaching: 'O treinador avalia cada lance seu assim que você o joga.',
    online:
      'Um adversário de verdade pelo Game Center, no relógio. Sem dicas, sem motor, sem voltar lances.',
    photo: 'Ler um tabuleiro de uma foto',
    takeOver: 'Continuar a partir daqui',
    freeForever:
      'Jogar continua de graça — contra o motor e contra pessoas, sem limite e sem anúncios. O que o Pro desbloqueia é o treino.',
    allowance:
      'A cota reinicia todo dia às 9h, horário local. Jogar — contra o motor ou contra uma pessoa — não tem limite e não custa nada.',
    noAds: 'Sem anúncios, em nenhuma parte do aplicativo, nunca',
    unlimitedPuzzles: 'Todos os 14.351 exercícios, quantos você quiser por dia',
    unlimitedRush: 'Séries de Rush sem limite diário',
    unlimitedRest: 'Julgamento posicional, finais e Adivinhe o Elo, sem limite',
    renewal:
      'O plano mensal renova todo mês até você cancelar. Dá para cancelar quando quiser em Ajustes › Conta Apple › Assinaturas, pelo menos um dia antes da renovação. A compra única é um pagamento só e nunca renova.',
    pro: 'Brass Pawn Pro',
    monthly: 'Mensal',
    lifetime: 'Compra única',
    privacyPolicy: 'Política de Privacidade',
    termsOfUse: 'Termos de Uso',
    licence: 'Licença',
    credits: 'Agradecimentos',
  },
  modes: {
    play: 'Jogar',
    watch: 'Assistir',
    tactics: 'Tática',
    positional: 'Posicional',
    endgames: 'Finais',
    guess: 'Adivinhe o Elo',
    online: 'On-line',
    progress: 'Progresso',
    rush: 'Rush',
  },
  shots: {
    title: ['Cada lance que você faz,', 'explicado.'],
    mistake: ['Não diz apenas', 'que você perdeu.'],
    values: ['Quanto vale cada lance.', 'Antes de jogá-lo.'],
    library: ['Novecentas partidas', 'que valem a pena assistir.'],
    engines: ['Dois motores.', 'Uma segunda opinião.'],
    coached: ['E quando você acerta,', 'ele diz.'],
    free: ['Cinco de cada,', 'de graça.'],
  },
  spoken: {
    watch:
      'Novecentas partidas que valem a pena assistir. Escolha uma, acompanhe — e assim que você jogaria diferente, assuma.',
    tactics:
      'Quatorze mil exercícios, escolhidos pelo que você erra. E então você vê quanto vale cada lance — antes de jogá-lo.',
    play: 'O jeito mais rápido de melhorar no xadrez? Saber por que cada lance funcionou. O Brass Pawn te diz — lance a lance.',
  },
  ui: {
    category: 'um treinador de xadrez para iPhone e iPad',
    support: 'Suporte',
    language: 'Idioma',
    menu: 'Menu',
    close: 'Fechar',
    film: 'Veja funcionando',
    screens: 'Cada tela',
    price: 'Quanto custa',
    questions: 'Perguntas',
    narrated: 'Com narração',
    silent: 'Sem som',
    play: 'Reproduzir',
    pause: 'Pausar',
    download: 'Baixar na App Store',
    soon: 'Em breve na App Store',
    more: 'Mais sobre o app',
    free: 'Grátis todo dia',
    faq: [
      'Precisa de conexão com a internet?',
      'O que é grátis?',
      'Como funciona a assinatura?',
      'Posso ver o código-fonte?',
    ],
    prices:
      'Os preços exibidos são da App Store dos EUA. Seu preço local é definido pela App Store.',
  },
};
