// Romanian (ro). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Joacă · Antrenează · Privește',
    lede: 'Tactică, judecată pozițională, tehnică de final și partide cu antrenor, cu motorul rulând chiar pe dispozitiv. Nimic nu părăsește telefonul.',
    privacy:
      'Aplicația nu colectează nimic, nu trimite nimic și nu face cereri de rețea. Ratingurile și istoricul rămân doar pe acest dispozitiv și dispar odată cu aplicația.',
    freeSoftware:
      'Această aplicație este software liber, licențiat sub GNU Affero General Public License versiunea 3 sau ulterioară.',
    stockfish:
      'Aplicația include Stockfish, publicat sub GPLv3. Fiindcă Stockfish este legat în aplicație, întreaga aplicație poartă aceeași licență — iar codul ei sursă complet este publicat.',
    reckless:
      'Include și Reckless, un al doilea motor, sub licența AGPLv3. Cele două licențe se combină, iar clauza Affero despre software-ul folosit printr-o rețea nu schimbă nimic aici: ambele motoare rulează pe acest dispozitiv, iar aplicația nu face nicio cerere de rețea.',
    coaching: 'Antrenorul evaluează fiecare mutare a ta imediat ce o faci.',
    online:
      'Un adversar real prin Game Center, cu ceas. Fără indicii, fără motor, fără mutări luate înapoi.',
    photo: 'Citește o tablă dintr-o fotografie',
    takeOver: 'Continuă de aici',
    freeForever:
      'Jocul rămâne gratuit — și cu motorul, și cu oameni, fără limită și fără reclame. Ce deblochează Pro este antrenamentul.',
    allowance:
      'Cota se resetează în fiecare zi la ora 9:00, ora locală. Jocul — cu motorul sau cu o persoană — este nelimitat și gratuit.',
    noAds: 'Nicio reclamă, în nicio parte a aplicației, niciodată',
    unlimitedPuzzles: 'Toate cele 14.351 de exerciții, câte vrei pe zi',
    unlimitedRush: 'Runde Rush fără limită zilnică',
    unlimitedRest: 'Judecată pozițională, finaluri și Ghicește Elo, fără limită',
    renewal:
      'Planul lunar se reînnoiește în fiecare lună până îl anulezi. Poți anula oricând din Setări › Cont Apple › Abonamente, cu cel puțin o zi înainte de reînnoire. Deblocarea unică este o singură plată și nu se reînnoiește niciodată.',
    pro: 'Brass Pawn Pro',
    monthly: 'Lunar',
    lifetime: 'Plată unică',
    privacyPolicy: 'Politica de confidențialitate',
    termsOfUse: 'Termeni de utilizare',
    licence: 'Licență',
    credits: 'Colaboratori',
  },
  modes: {
    play: 'Joacă',
    watch: 'Privește',
    tactics: 'Tactică',
    positional: 'Pozițional',
    endgames: 'Finaluri',
    guess: 'Ghicește Elo',
    online: 'Online',
    progress: 'Progres',
    rush: 'Rush',
  },
  shots: {
    title: ['Fiecare mutare a ta,', 'explicată.'],
    mistake: ['Nu-ți spune doar', 'că ai pierdut.'],
    values: ['Cât valorează fiecare mutare.', 'Înainte s-o faci.'],
    library: ['Nouă sute de partide', 'care merită văzute.'],
    engines: ['Două motoare.', 'O a doua părere.'],
    coached: ['Iar când nimerești,', 'ți-o spune.'],
    free: ['Câte cinci din fiecare,', 'gratuit.'],
  },
  spoken: {
    watch:
      'Nouă sute de partide care merită văzute. Alege una, urmărește-o — și din clipa în care ai fi mutat altfel, preia tu.',
    tactics:
      'Paisprezece mii de exerciții, alese din ce greșești. Și apoi vezi cât valorează fiecare mutare — înainte s-o faci.',
    play: 'Cel mai rapid mod de a progresa la șah? Să știi de ce a funcționat fiecare mutare. Brass Pawn îți spune — mutare cu mutare.',
  },
  ui: {
    category: 'un antrenor de șah pentru iPhone și iPad',
    support: 'Asistență',
    language: 'Limbă',
    menu: 'Meniu',
    close: 'Închide',
    film: 'Vezi-o în acțiune',
    screens: 'Fiecare ecran',
    price: 'Cât costă',
    questions: 'Întrebări',
    narrated: 'Cu naratoare',
    silent: 'Fără sunet',
    play: 'Redare',
    pause: 'Pauză',
    download: 'Descarcă din App Store',
    soon: 'În curând în App Store',
    more: 'Mai multe despre aplicație',
    free: 'Gratuit în fiecare zi',
    faq: [
      'Are nevoie de conexiune la internet?',
      'Ce este gratuit?',
      'Cum funcționează abonamentul?',
      'Pot vedea codul sursă?',
    ],
    prices:
      'Prețurile afișate sunt cele din App Store-ul american. Prețul tău local este stabilit de App Store.',
  },
};
