// Swedish (sv). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Spela · Träna · Se',
    lede: 'Taktik, positionsbedömning, slutspelsteknik och partier med coachning, med motorn igång på själva enheten. Ingenting lämnar telefonen.',
    privacy:
      'Appen samlar inte in något, skickar inget och gör inga nätverksanrop. Dina ratings och din historik finns bara på den här enheten och försvinner med appen.',
    freeSoftware:
      'Den här appen är fri programvara, licensierad under GNU Affero General Public License version 3 eller senare.',
    stockfish:
      'Appen innehåller Stockfish, som ges ut under GPLv3. Eftersom Stockfish är länkat in i appen omfattas hela appen av samma licens — och dess fullständiga källkod är publicerad.',
    reckless:
      'Appen innehåller även Reckless, en andra motor, under AGPLv3. De två licenserna går att kombinera, och Affero-klausulen om programvara som används över ett nätverk ändrar ingenting här: båda motorerna körs på den här enheten och appen gör inga nätverksanrop.',
    coaching: 'Tränaren bedömer vart och ett av dina drag allteftersom du gör dem.',
    online:
      'En riktig motståndare via Game Center, med klocka. Inga tips, ingen motor, inga återtagna drag.',
    photo: 'Läs ett bräde från ett foto',
    takeOver: 'Spela vidare härifrån',
    freeForever:
      'Att spela förblir gratis — mot motorn och mot människor, utan gräns och utan reklam. Det Pro låser upp är träningen.',
    allowance:
      'Kvoten nollställs varje dag kl. 09.00 lokal tid. Att spela — mot motorn eller mot en människa — är obegränsat och gratis.',
    noAds: 'Ingen reklam, ingenstans i appen, aldrig',
    unlimitedPuzzles: 'Alla 14 351 uppgifter, hur många om dagen du vill',
    unlimitedRush: 'Rush-rundor utan daglig gräns',
    unlimitedRest: 'Positionsbedömning, slutspelsövningar och Gissa ratingen, utan gräns',
    renewal:
      'Månadsplanen förnyas varje månad tills du säger upp den. Du kan säga upp när som helst i Inställningar › Apple-konto › Prenumerationer, senast en dag före förnyelsen. Engångsköpet är en enda betalning och förnyas aldrig.',
    pro: 'Brass Pawn Pro',
    monthly: 'Månadsvis',
    lifetime: 'Engångsköp',
    privacyPolicy: 'Integritetspolicy',
    termsOfUse: 'Användarvillkor',
    licence: 'Licens',
    credits: 'Medverkande',
  },
  modes: {
    play: 'Spela',
    watch: 'Se',
    tactics: 'Taktik',
    positional: 'Position',
    endgames: 'Slutspel',
    guess: 'Gissa ratingen',
    online: 'Online',
    progress: 'Utveckling',
    rush: 'Rush',
  },
  shots: {
    title: ['Varje drag du gör,', 'uppläst.'],
    mistake: ['Den säger inte bara', 'att du förlorade.'],
    values: ['Vad varje drag är värt.', 'Innan du drar.'],
    library: ['Niohundra partier', 'värda att se.'],
    engines: ['Två motorer.', 'En andra åsikt.'],
    coached: ['Och när du träffar rätt,', 'säger den det.'],
    free: ['Fem av varje,', 'gratis.'],
  },
  spoken: {
    watch:
      'Niohundra partier värda att se. Hitta ett, följ det — och i det ögonblick du hade dragit annorlunda, ta över.',
    tactics:
      'Fjortontusen övningar, valda utifrån det du missar. Och sen ser du vad varje drag är värt — innan du drar.',
    play: 'Snabbaste vägen till bättre schack? Att veta varför varje drag fungerade. Brass Pawn berättar det — drag för drag.',
  },
  ui: {
    category: 'en schacktränare för iPhone och iPad',
    support: 'Support',
    language: 'Språk',
    menu: 'Meny',
    close: 'Stäng',
    film: 'Se den i arbete',
    screens: 'Varje skärm',
    price: 'Vad det kostar',
    questions: 'Frågor',
    narrated: 'Med berättarröst',
    silent: 'Utan ljud',
    play: 'Spela upp',
    pause: 'Paus',
    download: 'Ladda ned på App Store',
    soon: 'Snart på App Store',
    more: 'Mer om appen',
    free: 'Gratis varje dag',
    faq: [
      'Krävs internetanslutning?',
      'Vad är gratis?',
      'Hur fungerar prenumerationen?',
      'Kan jag se källkoden?',
    ],
    prices:
      'Priserna som visas är från amerikanska App Store. Ditt lokala pris sätts av App Store.',
  },
};
