// Turkish (tr). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Oyna · Çalış · İzle',
    lede: 'Taktik, konum değerlendirmesi, oyunsonu tekniği ve koçluk eşliğinde oyun; motor cihazın kendisinde çalışır. Hiçbir şey telefondan çıkmaz.',
    privacy:
      'Uygulama hiçbir şey toplamaz, hiçbir şey göndermez ve ağ isteği yapmaz. Puanların ve geçmişin yalnızca bu cihazda durur; uygulamayı silmek onları da siler.',
    freeSoftware:
      'Bu uygulama özgür yazılımdır; GNU General Public License sürüm 3 veya sonrası ile lisanslanmıştır.',
    stockfish:
      "Uygulama, GPLv3 ile dağıtılan Stockfish'i içerir. Stockfish uygulamaya bağlandığı için tüm uygulama aynı lisansı taşır — ve kaynak kodunun tamamı yayımlanmıştır.",
    reckless:
      "Uygulama ayrıca AGPLv3 lisanslı ikinci bir motor olan Reckless'i de içerir. İki lisans birleşebilir ve ağ üzerinden kullanılan yazılıma dair Affero maddesi burada hiçbir şeyi değiştirmez: her iki motor da bu cihazda çalışır ve uygulama hiçbir ağ isteği yapmaz.",
    coaching: 'Antrenör, yaptığınız her hamleyi anında değerlendirir.',
    online:
      'Game Center üzerinden gerçek bir rakip, saatle. İpucu yok, motor yok, hamle geri alma yok.',
    photo: 'Fotoğraftan tahta oku',
    takeOver: 'Buradan devam et',
    freeForever:
      "Oynamak ücretsiz kalır — motora karşı da insana karşı da, sınırsız ve reklamsız. Pro'nun açtığı şey antrenman.",
    allowance:
      "Hak her gün yerel saatle 09.00'da yenilenir. Oynamak — motora ya da bir insana karşı — sınırsızdır ve hiçbir şey gerektirmez.",
    noAds: 'Uygulamanın hiçbir yerinde, hiçbir zaman reklam yok',
    unlimitedPuzzles: '14.351 problemin tamamı, günde istediğin kadar',
    unlimitedRush: 'Günlük sınırı olmayan Rush turları',
    unlimitedRest: 'Konum değerlendirmesi, oyunsonu alıştırmaları ve Elo tahmini, sınırsız',
    renewal:
      'Aylık plan, iptal edene kadar her ay yenilenir. Ayarlar › Apple Hesabı › Abonelikler bölümünden, yenilemeden en az bir gün önce dilediğin zaman iptal edebilirsin. Tek seferlik açma tek bir ödemedir ve asla yenilenmez.',
    pro: 'Brass Pawn Pro',
    monthly: 'Aylık',
    lifetime: 'Tek seferlik',
    privacyPolicy: 'Gizlilik Politikası',
    termsOfUse: 'Kullanım Koşulları',
    licence: 'Lisans',
    credits: 'Emeği geçenler',
  },
  modes: {
    play: 'Oyna',
    watch: 'İzle',
    tactics: 'Taktik',
    positional: 'Konumsal',
    endgames: 'Oyunsonu',
    guess: "Elo'yu tahmin et",
    online: 'Çevrimiçi',
    progress: 'İlerleme',
    rush: 'Rush',
  },
  shots: {
    title: ['Yaptığın her hamle,', 'sana okunuyor.'],
    mistake: ['Sadece kaybettiğini', 'söylemiyor.'],
    values: ['Her hamlenin değeri.', 'Oynamadan önce.'],
    library: ['İzlemeye değer', 'dokuz yüz parti.'],
    engines: ['İki motor.', 'İkinci bir görüş.'],
    coached: ['Doğru bulduğunda da,', 'söylüyor.'],
    free: ['Her birinden beş,', 'ücretsiz.'],
  },
  spoken: {
    watch:
      'İzlemeye değer dokuz yüz parti. Birini bul, takip et — ve farklı oynayacağın anda devral.',
    tactics:
      'On dört bin bulmaca, sürekli yanıldığın yerlerden seçilmiş. Sonra her hamlenin değerini görüyorsun — oynamadan önce.',
    play: 'Satrançta en hızlı gelişme yolu? Her hamlenin neden işe yaradığını bilmek. Brass Pawn size söyler — hamle hamle.',
  },
  ui: {
    category: 'iPhone ve iPad için bir satranç antrenörü',
    support: 'Destek',
    language: 'Dil',
    menu: 'Menü',
    close: 'Kapat',
    skip: 'İçeriğe geç',
    inEnglish: 'İngilizce',
    film: 'Çalışırken izle',
    screens: 'Her ekran',
    price: 'Ne kadar',
    questions: 'Sorular',
    narrated: 'Anlatımlı',
    silent: 'Sessiz',
    play: 'Oynat',
    pause: 'Duraklat',
    download: "App Store'dan indirin",
    soon: "Yakında App Store'da",
    more: 'Uygulama hakkında daha fazlası',
    free: 'Her gün ücretsiz',
    faq: [
      'İnternet bağlantısı gerekiyor mu?',
      'Ücretsiz olan ne?',
      'Abonelik nasıl işliyor?',
      'Kaynak kodunu görebilir miyim?',
    ],
    prices: 'Gösterilen fiyatlar ABD App Store fiyatlarıdır. Yerel fiyatını App Store belirler.',
  },
};
