// Vietnamese (vi). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: 'Chơi · Luyện · Xem',
    lede: 'Chiến thuật, đánh giá thế cờ, kỹ thuật tàn cuộc và các ván có huấn luyện viên, với engine chạy ngay trên máy. Không có gì rời khỏi điện thoại.',
    privacy:
      'Ứng dụng không thu thập gì, không gửi gì và không thực hiện yêu cầu mạng nào. Hệ số và lịch sử của bạn chỉ nằm trên máy này và sẽ mất khi gỡ ứng dụng.',
    freeSoftware:
      'Ứng dụng này là phần mềm tự do, theo giấy phép GNU Affero General Public License phiên bản 3 hoặc mới hơn.',
    stockfish:
      'Ứng dụng có kèm Stockfish, phát hành theo GPLv3. Vì Stockfish được liên kết vào ứng dụng nên toàn bộ ứng dụng mang cùng giấy phép — và mã nguồn đầy đủ đã được công bố.',
    reckless:
      'Ứng dụng cũng bao gồm Reckless, một engine thứ hai, theo giấy phép AGPLv3. Hai giấy phép có thể kết hợp, và điều khoản Affero về phần mềm được dùng qua mạng không thay đổi gì ở đây: cả hai engine đều chạy trên thiết bị này và ứng dụng không thực hiện bất kỳ yêu cầu mạng nào.',
    coaching: 'Huấn luyện viên chấm điểm từng nước đi của bạn ngay khi bạn đi.',
    online: 'Đối thủ thật qua Game Center, có đồng hồ. Không gợi ý, không máy, không đi lại nước.',
    photo: 'Đọc bàn cờ từ ảnh',
    takeOver: 'Chơi tiếp từ đây',
    freeForever:
      'Chơi cờ vẫn miễn phí — với máy hay với người, không giới hạn và không quảng cáo. Pro mở khóa phần luyện tập.',
    allowance:
      'Hạn mức đặt lại mỗi ngày lúc 9:00 giờ địa phương. Chơi cờ — với máy hay với người — không giới hạn và miễn phí.',
    noAds: 'Không quảng cáo, ở bất cứ đâu trong ứng dụng, mãi mãi',
    unlimitedPuzzles: 'Toàn bộ 14.351 bài tập, mỗi ngày bao nhiêu tùy bạn',
    unlimitedRush: 'Lượt Rush không giới hạn mỗi ngày',
    unlimitedRest: 'Đánh giá thế cờ, bài tàn cuộc và Đoán hệ số — không giới hạn',
    renewal:
      'Gói tháng tự gia hạn hằng tháng cho đến khi bạn hủy. Có thể hủy bất cứ lúc nào trong Cài đặt › Tài khoản Apple › Đăng ký, chậm nhất một ngày trước khi gia hạn. Gói mua một lần chỉ thanh toán một lần và không bao giờ gia hạn.',
    pro: 'Brass Pawn Pro',
    monthly: 'Hằng tháng',
    lifetime: 'Mua một lần',
    privacyPolicy: 'Chính sách quyền riêng tư',
    termsOfUse: 'Điều khoản sử dụng',
    licence: 'Giấy phép',
    credits: 'Đóng góp',
  },
  modes: {
    play: 'Chơi',
    watch: 'Xem',
    tactics: 'Chiến thuật',
    positional: 'Thế trận',
    endgames: 'Tàn cuộc',
    guess: 'Đoán hệ số',
    online: 'Trực tuyến',
    progress: 'Tiến bộ',
    rush: 'Rush',
  },
  shots: {
    title: ['Mỗi nước bạn đi,', 'được đọc lại.'],
    mistake: ['Không chỉ nói', 'rằng bạn đã thua.'],
    values: ['Giá trị của từng nước.', 'Trước khi bạn đi.'],
    library: ['Chín trăm ván cờ', 'đáng xem.'],
    engines: ['Hai engine.', 'Ý kiến thứ hai.'],
    coached: ['Và khi bạn đi đúng,', 'nó cũng nói.'],
    free: ['Mỗi loại năm lần,', 'miễn phí.'],
  },
  spoken: {
    watch:
      'Chín trăm ván cờ đáng xem. Chọn một ván, theo dõi — và ngay khi bạn sẽ đi khác, hãy tiếp quản.',
    tactics:
      'Mười bốn nghìn thế cờ, chọn từ những chỗ bạn hay sai. Rồi thấy giá trị của từng nước — trước khi đi.',
    play: 'Cách nhanh nhất để chơi cờ giỏi hơn? Biết vì sao mỗi nước đi hiệu quả. Brass Pawn cho bạn biết — từng nước một.',
  },
  ui: {
    category: 'huấn luyện viên cờ vua cho iPhone và iPad',
    support: 'Hỗ trợ',
    language: 'Ngôn ngữ',
    menu: 'Menu',
    close: 'Đóng',
    film: 'Xem ứng dụng hoạt động',
    screens: 'Mọi màn hình',
    price: 'Giá bao nhiêu',
    questions: 'Câu hỏi',
    narrated: 'Có lời dẫn',
    silent: 'Không tiếng',
    play: 'Phát',
    pause: 'Tạm dừng',
    download: 'Tải về trên App Store',
    soon: 'Sắp có trên App Store',
    more: 'Tìm hiểu thêm về ứng dụng',
    free: 'Miễn phí mỗi ngày',
    faq: [
      'Có cần kết nối internet không?',
      'Những gì được miễn phí?',
      'Gói đăng ký hoạt động thế nào?',
      'Tôi có thể xem mã nguồn không?',
    ],
    prices: 'Giá hiển thị là giá của App Store Mỹ. Giá tại nước bạn do App Store ấn định.',
  },
};
