// Chinese (Traditional) (zh-Hant). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: '對弈 · 訓練 · 觀戰',
    lede: '戰術、局面判斷、殘局技術與附講解的對局，引擎 直接在裝置上執行。沒有任何資料離開手機。',
    privacy:
      '本 App 不蒐集任何資料、不傳送任何資料，也不進行網路連線。你的等級分與紀錄只存在這台裝置上，刪除 App 就一併刪除。',
    freeSoftware: '本 App 是自由軟體，依 GNU General Public License 第 3 版或更新版本授權。',
    stockfish:
      '本 App 內含以 GPLv3 發布的 Stockfish。由於 Stockfish 連結進 App，整個 App 採用相同授權，其完整原始碼已公開。',
    reckless:
      '本應用程式還包含第二個引擎 Reckless，其授權為 AGPLv3。兩種授權可以並存，而 Affero 中關於透過網路使用軟體的條款在這裡沒有任何影響：兩個引擎都在本機執行，應用程式不發出任何網路請求。',
    coaching: '教練會在你每走一步時立即為其評分。',
    online: '透過 Game Center 與真人對弈，附計時。沒有提示，沒有引擎，不能悔棋。',
    photo: '從照片讀取棋盤',
    takeOver: '從這裡續下',
    freeForever: '對弈始終免費——不論對手是引擎還是真人，不限次數，也沒有廣告。Pro 解鎖的是訓練。',
    allowance:
      '額度每天上午 9 點（當地時間）重置。對弈——不論對手是引擎還是真人——不限次數，也不收費。',
    noAds: 'App 任何角落都沒有廣告，永遠沒有',
    unlimitedPuzzles: '全部 14,351 道題，每天想做多少就做多少',
    unlimitedRush: '衝刺不限每日次數',
    unlimitedRest: '局面判斷、殘局練習與猜等級分，全部不限量',
    renewal:
      '月方案在你取消前每月自動續訂。可隨時在「設定 › Apple 帳號 › 訂閱項目」中取消，最遲在續訂前一天。一次買斷只付一次，永不續訂。',
    pro: 'Brass Pawn Pro',
    monthly: '每月',
    lifetime: '一次買斷',
    privacyPolicy: '隱私權政策',
    termsOfUse: '使用條款',
    licence: '授權',
    credits: '參與者',
  },
  modes: {
    play: '對弈',
    watch: '觀戰',
    tactics: '戰術',
    positional: '局面',
    endgames: '殘局',
    guess: '猜等級分',
    online: '線上',
    progress: '進度',
    rush: '衝刺',
  },
  shots: {
    title: ['你走的每一步，', '都講給你聽。'],
    mistake: ['不只是告訴你', '輸了。'],
    values: ['每一步值多少。', '落子之前。'],
    library: ['九百局', '值得一看的對局。'],
    engines: ['兩個引擎。', '第二種意見。'],
    coached: ['走對了的時候，', '它也會說。'],
    free: ['每樣五次，', '免費。'],
  },
  spoken: {
    watch: '九百局值得一看的對局。挑一局跟下去，到你會走出不同一步的那一刻，就由你接手。',
    tactics: '一萬四千道題，從你反覆出錯的地方挑出來。然後每一步值多少，落子之前就看得見。',
    play: '最快提升棋力的方法？知道每一步為什麼好。Brass Pawn 會告訴你——一步一步。',
  },
  ui: {
    category: '一款 iPhone 和 iPad 上的西洋棋教練',
    support: '支援',
    language: '語言',
    menu: '選單',
    close: '關閉',
    skip: '跳至內容',
    inEnglish: '英文',
    film: '看它怎麼運作',
    screens: '每一個畫面',
    price: '價格',
    questions: '常見問題',
    narrated: '含旁白',
    silent: '靜音',
    play: '播放',
    pause: '暫停',
    download: '從 App Store 下載',
    soon: '即將登陸 App Store',
    more: '了解更多',
    free: '每天都有免費額度',
    faq: ['需要連網嗎？', '免費的部分有哪些？', '訂閱是怎麼算的？', '可以看到原始碼嗎？'],
    prices: '顯示的是美國 App Store 價格。你所在地區的價格由 App Store 決定。',
  },
};
