// Chinese (Simplified) (zh-Hans). Generated by tools/harvest-copy.py — do not edit.
//
// `said`, `modes`, `shots` and `spoken` were already translated: for the app's
// own screens, for its App Store page, and for the narrator to read aloud. The
// website repeats them word for word rather than translating the same claims a
// second time, so the sentence that persuaded somebody here is still there,
// unchanged, in the app they install.
//
// `ui` is the remainder — the two dozen strings that exist only on a website —
// and it is written by hand in tools/manual.json.

import type { Copy } from '../types';

export const copy: Copy = {
  said: {
    slug: '对弈 · 训练 · 观战',
    lede: '战术、局面判断、残局技术和带讲解的对局，引擎 直接在设备上运行。没有任何数据离开手机。',
    privacy:
      '本应用不收集任何数据，不发送任何数据，也不进行网络请求。你的等级分和记录只存在这台设备上，删除应用即一并删除。',
    freeSoftware: '本应用是自由软件，依 GNU General Public License 第 3 版或更新版本授权。',
    stockfish:
      '本应用包含以 GPLv3 发布的 Stockfish。由于 Stockfish 被链接进应用，整个应用采用同一许可协议，其完整源代码已经公开。',
    reckless:
      '本应用还包含第二个引擎 Reckless，其许可证为 AGPLv3。两种许可证可以并存，而 Affero 中关于通过网络使用软件的条款在这里没有任何影响：两个引擎都在本机运行，应用不发出任何网络请求。',
    coaching: '教练会在你每走一步时立即为其评分。',
    online: '通过 Game Center 与真人对弈，带计时。没有提示，没有引擎，不能悔棋。',
    photo: '从照片读取棋盘',
    takeOver: '从这里续下',
    freeForever: '对弈始终免费——无论对手是引擎还是真人，不限次数，也没有广告。Pro 解锁的是训练。',
    allowance:
      '额度每天上午 9 点（当地时间）重置。对弈——无论对手是引擎还是真人——不限次数，也不收费。',
    noAds: '应用任何角落都没有广告，永远没有',
    unlimitedPuzzles: '全部 14,351 道题，每天想做多少做多少',
    unlimitedRush: '冲刺不限每日次数',
    unlimitedRest: '局面判断、残局练习和猜等级分，全部不限量',
    renewal:
      '月度方案在你取消前每月自动续订。可随时在「设置 › Apple 账户 › 订阅」中取消，最迟在续订前一天。一次买断只付一次，永不续订。',
    pro: 'Brass Pawn Pro',
    monthly: '按月',
    lifetime: '一次买断',
    privacyPolicy: '隐私政策',
    termsOfUse: '使用条款',
    licence: '许可协议',
    credits: '参与者',
  },
  modes: {
    play: '对弈',
    watch: '观战',
    tactics: '战术',
    positional: '局面',
    endgames: '残局',
    guess: '猜等级分',
    online: '在线',
    progress: '进度',
    rush: '冲刺',
  },
  shots: {
    title: ['你走的每一步，', '都讲给你听。'],
    mistake: ['不只是告诉你', '输了。'],
    values: ['每一步值多少。', '落子之前。'],
    library: ['九百局', '值得一看的对局。'],
    engines: ['两个引擎。', '第二种意见。'],
    coached: ['走对了的时候，', '它也会说。'],
    free: ['每样五次，', '免费。'],
  },
  spoken: {
    watch: '九百局值得一看的对局。挑一局跟下去，到你会走出不同一步的那一刻，就由你接手。',
    tactics: '一万四千道题，从你反复出错的地方挑出来。然后每一步值多少，落子之前就看得见。',
    play: '最快提升棋力的方法？知道每一步为什么好。Brass Pawn 会告诉你——一步一步。',
  },
  ui: {
    category: '一款 iPhone 和 iPad 上的国际象棋教练',
    support: '支持',
    language: '语言',
    menu: '菜单',
    close: '关闭',
    film: '看它怎么运作',
    screens: '每一个界面',
    price: '价格',
    questions: '常见问题',
    narrated: '带解说',
    silent: '静音',
    play: '播放',
    pause: '暂停',
    download: '从 App Store 下载',
    soon: '即将登陆 App Store',
    more: '了解更多',
    free: '每天都有免费额度',
    faq: ['需要联网吗？', '免费的部分有哪些？', '订阅是怎么算的？', '可以看到源代码吗？'],
    prices: '显示的是美国 App Store 价格。你所在地区的价格由 App Store 决定。',
  },
};
