// Generated by tools/harvest-copy.py — do not edit.
//
// A static map of dynamic imports, which is the form the bundler can see
// through: it splits each language into its own chunk, and a visitor to the
// Japanese page downloads Japanese and nothing else. A computed import path
// would defeat that and ship all thirty-one.

import type { Copy } from './types';

export const COPY: Record<string, () => Promise<Copy>> = {
  en: () => import('./copy/en').then((m) => m.copy),
  'en-ca': () => import('./copy/en-ca').then((m) => m.copy),
  ar: () => import('./copy/ar').then((m) => m.copy),
  cs: () => import('./copy/cs').then((m) => m.copy),
  da: () => import('./copy/da').then((m) => m.copy),
  de: () => import('./copy/de').then((m) => m.copy),
  el: () => import('./copy/el').then((m) => m.copy),
  es: () => import('./copy/es').then((m) => m.copy),
  fi: () => import('./copy/fi').then((m) => m.copy),
  fr: () => import('./copy/fr').then((m) => m.copy),
  'fr-ca': () => import('./copy/fr-ca').then((m) => m.copy),
  he: () => import('./copy/he').then((m) => m.copy),
  hi: () => import('./copy/hi').then((m) => m.copy),
  hu: () => import('./copy/hu').then((m) => m.copy),
  id: () => import('./copy/id').then((m) => m.copy),
  it: () => import('./copy/it').then((m) => m.copy),
  ja: () => import('./copy/ja').then((m) => m.copy),
  ko: () => import('./copy/ko').then((m) => m.copy),
  ms: () => import('./copy/ms').then((m) => m.copy),
  nl: () => import('./copy/nl').then((m) => m.copy),
  no: () => import('./copy/no').then((m) => m.copy),
  pl: () => import('./copy/pl').then((m) => m.copy),
  'pt-br': () => import('./copy/pt-br').then((m) => m.copy),
  ro: () => import('./copy/ro').then((m) => m.copy),
  ru: () => import('./copy/ru').then((m) => m.copy),
  sv: () => import('./copy/sv').then((m) => m.copy),
  th: () => import('./copy/th').then((m) => m.copy),
  tr: () => import('./copy/tr').then((m) => m.copy),
  vi: () => import('./copy/vi').then((m) => m.copy),
  'zh-hans': () => import('./copy/zh-hans').then((m) => m.copy),
  'zh-hant': () => import('./copy/zh-hant').then((m) => m.copy),
  bg: () => import('./copy/bg').then((m) => m.copy),
};
