/**
 * Pull the webfonts down from Google and serve them ourselves.
 *
 * Three reasons, in order of how much they matter:
 *
 *   1. Two fewer origins on the critical path. A Google-hosted font costs a DNS
 *      lookup and a TLS handshake to fonts.googleapis.com for the stylesheet,
 *      then another pair to fonts.gstatic.com for the file — before the largest
 *      text on the page can be painted.
 *   2. A preload that stays correct. Google's file URLs carry a version hash
 *      that changes without warning, so a hand-copied `rel=preload` silently
 *      starts downloading a 404 while the stylesheet fetches something else.
 *   3. Nothing to disclose. A site whose whole argument is "it collects
 *      nothing" should not hand every visitor's IP address to a third party to
 *      draw its headings.
 *
 * Run when a face needs adding or the fonts need refreshing:
 *
 *   node tools/fetch-fonts.mjs
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const OUT = 'public/fonts';
const CSS_OUT = 'src/fonts.css';
const INDEX = 'src/index.html';

/** The two faces the title is set in, preloaded by name in index.html. */
const PRELOAD = ['cormorant-garamond-300-latin', 'cormorant-garamond-400-italic-latin'];

// A modern browser UA, or Google serves the ancient TTF stylesheet instead.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

// Only the faces the design actually uses, and only the subsets the copy needs.
// Every extra weight is a file that will be downloaded and never drawn with.
const FAMILIES = [
  'Cormorant+Garamond:ital,wght@0,300;0,400;1,400',
  'Inter:wght@300;400;500',
  'JetBrains+Mono:wght@400;500',
];
const SUBSETS = new Set(['latin', 'latin-ext']);

const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join('&')}&display=swap`;

const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts said ${r.status}`);
  return r.text();
});

// Wiped rather than merged, so a face dropped from FAMILIES stops being served
// instead of lingering as an orphan nothing references.
await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

// The stylesheet is a run of `/* subset */ @font-face { … }` blocks.
const blocks = css.split('/*').slice(1);
const kept = [];
const names = new Map();
let downloaded = 0;

for (const block of blocks) {
  const subset = block.slice(0, block.indexOf('*/')).trim();
  if (!SUBSETS.has(subset)) continue;

  const family = /font-family: '([^']+)'/.exec(block)?.[1];
  const style = /font-style: (\w+)/.exec(block)?.[1] ?? 'normal';
  const weight = /font-weight: (\d+)/.exec(block)?.[1] ?? '400';
  const src = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
  if (!family || !src) continue;

  const bytes = Buffer.from(await fetch(src).then((r) => r.arrayBuffer()));

  // The filename carries a hash of the contents, which is what lets the deploy
  // cache fonts for a year: a changed face is a different URL, so nobody is
  // ever left holding a stale one.
  const stem = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}${style === 'italic' ? '-italic' : ''}-${subset}`;
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8);
  const name = `${stem}.${hash}.woff2`;

  await writeFile(join(OUT, name), bytes);
  downloaded += bytes.length;
  names.set(stem, name);

  const range = /unicode-range: ([^;]+);/.exec(block)?.[1];
  kept.push(
    `@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: ${style};\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${name}') format('woff2');\n` +
      (range ? `  unicode-range: ${range};\n` : '') +
      `}`,
  );
}

await writeFile(
  CSS_OUT,
  `/* Generated by tools/fetch-fonts.mjs — do not edit. */\n\n${kept.join('\n\n')}\n`,
  'utf8',
);

// index.html preloads two faces by name. Rewriting them here rather than by
// hand is the whole reason hashing the filenames is safe to do at all.
let index = await readFile(INDEX, 'utf8');
for (const stem of PRELOAD) {
  const name = names.get(stem);
  if (!name) throw new Error(`${stem} is preloaded but was not downloaded`);
  index = index.replace(new RegExp(`fonts/${stem}\\.[a-f0-9]+\\.woff2`), `fonts/${name}`);
}
await writeFile(INDEX, index, 'utf8');

console.log(
  `fonts: ${kept.length} faces, ${(downloaded / 1024).toFixed(0)} kB → ${OUT}, ` +
    `rules → ${CSS_OUT}, ${PRELOAD.length} preloads rewritten in ${INDEX}`,
);
