#!/usr/bin/env python3
"""The app's own words for the Today pages, in every language the site has.

The story page names the same things the app's story screen does — White,
Black, the result, the key move, the engine's choice, the board's squares and
sets — and the app has them translated already, by people. So they are copied
from ios/App/Localizable.xcstrings rather than translated a second time, and a
word changed in the app changes on the site at the next run of this.

    python3 web/tools/today-app-words.py   →  web/src/app/pages/today/i18n/app-words.ts
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
CATALOGUE = json.loads((ROOT / "ios/App/Localizable.xcstrings").read_text())["strings"]

# The site's slug for each of the app's localisations.
SLUGS = {
    "en": "en", "en-CA": "en-ca", "ar-SA": "ar", "cs": "cs", "da": "da", "de-DE": "de", "el": "el",
    "es-ES": "es", "fi": "fi", "fr-FR": "fr", "fr-CA": "fr-ca", "he": "he", "hi": "hi", "hu": "hu",
    "id": "id", "it": "it", "ja": "ja", "ko": "ko", "ms": "ms", "nl-NL": "nl", "no": "no", "pl": "pl",
    "pt-BR": "pt-br", "ro": "ro", "ru": "ru", "sv": "sv", "th": "th", "tr": "tr", "vi": "vi",
    "zh-Hans": "zh-hans", "zh-Hant": "zh-hant",
}

KEYS = {
    "white": "color.white", "black": "color.black",
    "today": "today.title", "result": "today.result", "event": "today.event",
    "keyMove": "today.keyMove", "enginesChoice": "today.enginesChoice",
    "replay": "today.replay", "tryIt": "today.tryIt",
    "after": "today.after", "stockfish": "today.stockfish", "round": "today.round",
    "empty": "today.empty",
    "squares": "settings.squares", "pieces": "settings.pieces", "lightSide": "settings.lightSide",
    "set": "settings.carving",
    "banded": "settings.banded", "plain": "settings.plainSet", "parlour": "settings.parlourSet",
    "wood": "appearance.board.wood", "lamplight": "appearance.board.lamplight",
    "amber": "appearance.board.classic", "forest": "appearance.board.forest",
    "ocean": "appearance.board.ocean", "ivory": "appearance.board.ivory",
    "rose": "appearance.board.rose", "sand": "appearance.board.sand", "slate": "appearance.board.slate",
    "ebony": "appearance.pieces.ebony", "emerald": "appearance.pieces.emerald",
    "sapphire": "appearance.pieces.sapphire", "claret": "appearance.pieces.claret",
    "glyph": "appearance.pieces.glyph",
    "snow": "appearance.tone.snow", "chalk": "appearance.tone.chalk", "boxwood": "appearance.tone.boxwood",
    "frost": "appearance.tone.frost", "mist": "appearance.tone.mist",
}


def value(key, locale):
    entry = CATALOGUE[key].get("localizations", {})
    unit = entry.get(locale, {}).get("stringUnit") or entry.get("en", {}).get("stringUnit")
    text = unit["value"]
    # The catalogue's placeholders, as the site fills them.
    return text.replace("%1$@", "{0}").replace("%2$@", "{1}").replace("%@", "{0}").replace("%lld", "{0}")


out = {SLUGS[locale]: {field: value(key, locale) for field, key in KEYS.items()} for locale in SLUGS}
body = json.dumps(out, ensure_ascii=False, indent=2)
(ROOT / "web/src/app/pages/today/i18n/app-words.ts").write_text(
    "// Generated by web/tools/today-app-words.py from ios/App/Localizable.xcstrings — do not edit.\n\n"
    f"export const APP_WORDS: Record<string, Record<string, string>> = {body};\n"
)
print(f"{len(out)} languages, {len(KEYS)} words each")
